@ roclib veneer table — GENERATED by tools/clibspec/gen_veneers.py
@ One MOV pc,#0 per module entry; SharedCLibrary patches each slot
@ at LibInitAPCS_32.  Slot N is the module's Nth entry: order is the contract.

    .syntax unified
    .arm

    .section Stub$$Init
    .global _clib_stub_init
_clib_stub_init:
    .word 3          @ generation 3: 185 slots
    .word _clib3_start
    .word _clib3_end
    .word 0
    .word 0
    .word 5          @ generation 5: 189 slots
    .word _clib5_start
    .word _clib5_end
    .word 0
    .word 0
    .word -1               @ descriptor list terminator

    .section Stub$$Entries,"ax",%progbits
    .align 2
    .global _clib3_start
    .global _clib3_end
_clib3_start:
.global TrapHandler
TrapHandler:
    .word 0xE3A0F000
.global UncaughtTrapHandler
UncaughtTrapHandler:
    .word 0xE3A0F000
.global EventHandler
EventHandler:
    .word 0xE3A0F000
.global UnhandledEventHandler
UnhandledEventHandler:
    .word 0xE3A0F000
.global x$stack_overflow
.global __rt_stkovf_split_small
__rt_stkovf_split_small:
x$stack_overflow:
    .word 0xE3A0F000
.global x$stack_overflow_1
.global __rt_stkovf_split_big
__rt_stkovf_split_big:
x$stack_overflow_1:
    .word 0xE3A0F000
.global x$udivide
.global __rt_udiv
__rt_udiv:
x$udivide:
    .word 0xE3A0F000
.global x$uremainder
x$uremainder:
    .word 0xE3A0F000
.global x$divide
.global __rt_sdiv
__rt_sdiv:
x$divide:
    .word 0xE3A0F000
.global x$divtest
.global __rt_divtest
__rt_divtest:
x$divtest:
    .word 0xE3A0F000
.global x$remainder
x$remainder:
    .word 0xE3A0F000
.global x$multiply
x$multiply:
    .word 0xE3A0F000
.global _rd1chk
.global __rt_rd1chk
__rt_rd1chk:
_rd1chk:
    .word 0xE3A0F000
.global _rd2chk
.global __rt_rd2chk
__rt_rd2chk:
_rd2chk:
    .word 0xE3A0F000
.global _rd4chk
.global __rt_rd4chk
__rt_rd4chk:
_rd4chk:
    .word 0xE3A0F000
.global _wr1chk
.global __rt_wr1chk
__rt_wr1chk:
_wr1chk:
    .word 0xE3A0F000
.global _wr2chk
.global __rt_wr2chk
__rt_wr2chk:
_wr2chk:
    .word 0xE3A0F000
.global _wr4chk
.global __rt_wr4chk
__rt_wr4chk:
_wr4chk:
    .word 0xE3A0F000
.global _main
_main:
    .word 0xE3A0F000
.global _exit
_exit:
    .word 0xE3A0F000
.global _clib_initialise
_clib_initialise:
    .word 0xE3A0F000
.global _backtrace
_backtrace:
    .word 0xE3A0F000
.global _count
_count:
    .word 0xE3A0F000
.global _count1
_count1:
    .word 0xE3A0F000
.global _stfp
_stfp:
    .word 0xE3A0F000
.global _ldfp
_ldfp:
    .word 0xE3A0F000
.global _printf
_printf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global _fprintf
_fprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global _sprintf
_sprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global clock
clock:
    .word 0xE3A0F000
.global difftime
difftime:
    .word 0xE3A0F000 @ unsafe class: slot only
.global mktime
mktime:
    .word 0xE3A0F000
.global time
time:
    .word 0xE3A0F000
.global asctime
asctime:
    .word 0xE3A0F000
.global ctime
ctime:
    .word 0xE3A0F000
.global gmtime
gmtime:
    .word 0xE3A0F000
.global localtime
localtime:
    .word 0xE3A0F000
.global strftime
strftime:
    .word 0xE3A0F000
.global memcpy
memcpy:
    .word 0xE3A0F000
.global memmove
memmove:
    .word 0xE3A0F000
.global strcpy
strcpy:
    .word 0xE3A0F000
.global strncpy
strncpy:
    .word 0xE3A0F000
.global strcat
strcat:
    .word 0xE3A0F000
.global strncat
strncat:
    .word 0xE3A0F000
.global memcmp
memcmp:
    .word 0xE3A0F000
.global strcmp
strcmp:
    .word 0xE3A0F000
.global strncmp
strncmp:
    .word 0xE3A0F000
.global memchr
memchr:
    .word 0xE3A0F000
.global strchr
strchr:
    .word 0xE3A0F000
.global strcspn
strcspn:
    .word 0xE3A0F000
.global strpbrk
strpbrk:
    .word 0xE3A0F000
.global strrchr
strrchr:
    .word 0xE3A0F000
.global strspn
strspn:
    .word 0xE3A0F000
.global strstr
strstr:
    .word 0xE3A0F000
.global strtok
strtok:
    .word 0xE3A0F000
.global memset
memset:
    .word 0xE3A0F000
.global strerror
strerror:
    .word 0xE3A0F000
.global strlen
strlen:
    .word 0xE3A0F000
.global atof
atof:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atoi
atoi:
    .word 0xE3A0F000
.global atol
atol:
    .word 0xE3A0F000
.global strtod
strtod:
    .word 0xE3A0F000 @ unsafe class: slot only
.global strtol
strtol:
    .word 0xE3A0F000
.global strtoul
strtoul:
    .word 0xE3A0F000
.global rand
rand:
    .word 0xE3A0F000
.global srand
srand:
    .word 0xE3A0F000
.global calloc
calloc:
    .word 0xE3A0F000
.global free
free:
    .word 0xE3A0F000
.global malloc
malloc:
    .word 0xE3A0F000
.global realloc
realloc:
    .word 0xE3A0F000
.global abort
abort:
    .word 0xE3A0F000
.global atexit
atexit:
    .word 0xE3A0F000
.global exit
exit:
    .word 0xE3A0F000
.global getenv
getenv:
    .word 0xE3A0F000
.global system
system:
    .word 0xE3A0F000
.global bsearch
bsearch:
    .word 0xE3A0F000
.global qsort
qsort:
    .word 0xE3A0F000
.global abs
abs:
    .word 0xE3A0F000
.global div
div:
    .word 0xE3A0F000 @ unsafe class: slot only
.global labs
labs:
    .word 0xE3A0F000
.global ldiv
ldiv:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remove
remove:
    .word 0xE3A0F000
.global rename
rename:
    .word 0xE3A0F000
.global tmpfile
tmpfile:
    .word 0xE3A0F000
.global __old_tmpnam
__old_tmpnam:
    .word 0xE3A0F000
.global fclose
fclose:
    .word 0xE3A0F000
.global fflush
fflush:
    .word 0xE3A0F000
.global fopen
fopen:
    .word 0xE3A0F000
.global freopen
freopen:
    .word 0xE3A0F000
.global setbuf
setbuf:
    .word 0xE3A0F000
.global setvbuf
setvbuf:
    .word 0xE3A0F000
.global printf
printf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global fprintf
fprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global sprintf
sprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global scanf
scanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global fscanf
fscanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global sscanf
sscanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global vprintf
vprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vfprintf
vfprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vsprintf
vsprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global _vfprintf
_vfprintf:
    .word 0xE3A0F000
.global fgetc
fgetc:
    .word 0xE3A0F000
.global fgets
fgets:
    .word 0xE3A0F000
.global fputc
fputc:
    .word 0xE3A0F000
.global fputs
fputs:
    .word 0xE3A0F000
.global __filbuf
__filbuf:
    .word 0xE3A0F000
.global getc
getc:
    .word 0xE3A0F000
.global getchar
getchar:
    .word 0xE3A0F000
.global gets
gets:
    .word 0xE3A0F000
.global __flsbuf
__flsbuf:
    .word 0xE3A0F000
.global putc
putc:
    .word 0xE3A0F000
.global putchar
putchar:
    .word 0xE3A0F000
.global puts
puts:
    .word 0xE3A0F000
.global ungetc
ungetc:
    .word 0xE3A0F000
.global fread
fread:
    .word 0xE3A0F000
.global fwrite
fwrite:
    .word 0xE3A0F000
.global fgetpos
fgetpos:
    .word 0xE3A0F000
.global fseek
.global _fseeko
_fseeko:
fseek:
    .word 0xE3A0F000
.global fsetpos
fsetpos:
    .word 0xE3A0F000
.global ftell
.global _ftello
_ftello:
ftell:
    .word 0xE3A0F000
.global rewind
rewind:
    .word 0xE3A0F000
.global clearerr
clearerr:
    .word 0xE3A0F000
.global feof
feof:
    .word 0xE3A0F000
.global ferror
ferror:
    .word 0xE3A0F000
.global perror
perror:
    .word 0xE3A0F000
.global __ignore_signal_handler
__ignore_signal_handler:
    .word 0xE3A0F000
.global __default_signal_handler
__default_signal_handler:
    .word 0xE3A0F000
.global __error_signal_marker
__error_signal_marker:
    .word 0xE3A0F000
.global signal
signal:
    .word 0xE3A0F000
.global raise
raise:
    .word 0xE3A0F000
.global setjmp
setjmp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global longjmp
longjmp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global acos
acos:
    .word 0xE3A0F000 @ unsafe class: slot only
.global asin
asin:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atan
atan:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atan2
atan2:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cos
cos:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sin
sin:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tan
tan:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cosh
cosh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sinh
sinh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tanh
tanh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global exp
exp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global frexp
frexp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ldexp
ldexp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log
log:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log10
log10:
    .word 0xE3A0F000 @ unsafe class: slot only
.global modf
modf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global pow
pow:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sqrt
sqrt:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ceil
ceil:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fabs
fabs:
    .word 0xE3A0F000 @ unsafe class: slot only
.global floor
floor:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmod
fmod:
    .word 0xE3A0F000 @ unsafe class: slot only
.global setlocale
setlocale:
    .word 0xE3A0F000
.global isalnum
isalnum:
    .word 0xE3A0F000
.global isalpha
isalpha:
    .word 0xE3A0F000
.global iscntrl
iscntrl:
    .word 0xE3A0F000
.global isdigit
isdigit:
    .word 0xE3A0F000
.global isgraph
isgraph:
    .word 0xE3A0F000
.global islower
islower:
    .word 0xE3A0F000
.global isprint
isprint:
    .word 0xE3A0F000
.global ispunct
ispunct:
    .word 0xE3A0F000
.global isspace
isspace:
    .word 0xE3A0F000
.global isupper
isupper:
    .word 0xE3A0F000
.global isxdigit
isxdigit:
    .word 0xE3A0F000
.global tolower
tolower:
    .word 0xE3A0F000
.global toupper
toupper:
    .word 0xE3A0F000
.global __assert
__assert:
    .word 0xE3A0F000
.global _memcpy
_memcpy:
    .word 0xE3A0F000
.global _memset
_memset:
    .word 0xE3A0F000
.global localeconv
localeconv:
    .word 0xE3A0F000
.global mblen
mblen:
    .word 0xE3A0F000
.global mbtowc
mbtowc:
    .word 0xE3A0F000
.global wctomb
wctomb:
    .word 0xE3A0F000
.global mbstowcs
mbstowcs:
    .word 0xE3A0F000
.global wcstombs
wcstombs:
    .word 0xE3A0F000
.global strxfrm
strxfrm:
    .word 0xE3A0F000
.global strcoll
strcoll:
    .word 0xE3A0F000
.global _clib_finalisemodule
_clib_finalisemodule:
    .word 0xE3A0F000
.global _clib_version
_clib_version:
    .word 0xE3A0F000
.global _CLib_Finalise
_CLib_Finalise:
    .word 0xE3A0F000
.global tmpnam
tmpnam:
    .word 0xE3A0F000
.global _swi
_swi:
    .word 0xE3A0F000 @ unsafe class: slot only
.global _swix
_swix:
    .word 0xE3A0F000 @ unsafe class: slot only
_clib3_end:

    .global _clib5_start
    .global _clib5_end
_clib5_start:
.global __fpclassifyf
__fpclassifyf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global __fpclassifyd
__fpclassifyd:
    .word 0xE3A0F000 @ unsafe class: slot only
.global __signbitf
__signbitf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global __signbitd
__signbitd:
    .word 0xE3A0F000 @ unsafe class: slot only
.global __copysignd
__copysignd:
    .word 0xE3A0F000 @ unsafe class: slot only
.global __copysignf
__copysignf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nan
nan:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nanf
nanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nextafter
nextafter:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nextafterf
nextafterf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fdim
fdim:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fdimf
fdimf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmax
fmax:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmaxf
fmaxf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmin
fmin:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fminf
fminf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fabsf
fabsf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global hypot
hypot:
    .word 0xE3A0F000 @ unsafe class: slot only
.global hypotf
hypotf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global feclearexcept
feclearexcept:
    .word 0xE3A0F000
.global fegetexceptflag
fegetexceptflag:
    .word 0xE3A0F000
.global feraiseexcept
feraiseexcept:
    .word 0xE3A0F000
.global fesetexceptflag
fesetexceptflag:
    .word 0xE3A0F000
.global fetestexcept
fetestexcept:
    .word 0xE3A0F000
.global fegetround
fegetround:
    .word 0xE3A0F000
.global fesetround
fesetround:
    .word 0xE3A0F000
.global fegetenv
fegetenv:
    .word 0xE3A0F000
.global feholdexcept
feholdexcept:
    .word 0xE3A0F000
.global fesetenv
fesetenv:
    .word 0xE3A0F000
.global feupdateenv
feupdateenv:
    .word 0xE3A0F000
.global _snprintf
_snprintf:
    .word 0xE3A0F000
.global snprintf
snprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vsnprintf
vsnprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vfscanf
vfscanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vscanf
vscanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vsscanf
vsscanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ceilf
ceilf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global floorf
floorf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nearbyint
nearbyint:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nearbyintf
nearbyintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global rint
rint:
    .word 0xE3A0F000 @ unsafe class: slot only
.global rintf
rintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lrint
lrint:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lrintf
lrintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global round
round:
    .word 0xE3A0F000 @ unsafe class: slot only
.global roundf
roundf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lround
lround:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lroundf
lroundf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global trunc
trunc:
    .word 0xE3A0F000 @ unsafe class: slot only
.global truncf
truncf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remainder
remainder:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remainderf
remainderf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global llabs
llabs:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lldiv
lldiv:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atoll
atoll:
    .word 0xE3A0F000 @ unsafe class: slot only
.global strtoll
strtoll:
    .word 0xE3A0F000 @ unsafe class: slot only
.global strtoull
strtoull:
    .word 0xE3A0F000 @ unsafe class: slot only
.global imaxabs
imaxabs:
    .word 0xE3A0F000
.global imaxdiv
imaxdiv:
    .word 0xE3A0F000
.global strtoimax
strtoimax:
    .word 0xE3A0F000
.global strtoumax
strtoumax:
    .word 0xE3A0F000
.global __assert2
__assert2:
    .word 0xE3A0F000
.global _Exit
_Exit:
    .word 0xE3A0F000
.global acosf
acosf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global asinf
asinf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atanf
atanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atan2f
atan2f:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cosf
cosf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sinf
sinf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tanf
tanf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global acosh
acosh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global acoshf
acoshf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global asinh
asinh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global asinhf
asinhf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atanh
atanh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atanhf
atanhf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global expf
expf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global exp2
exp2:
    .word 0xE3A0F000 @ unsafe class: slot only
.global exp2f
exp2f:
    .word 0xE3A0F000 @ unsafe class: slot only
.global expm1
expm1:
    .word 0xE3A0F000 @ unsafe class: slot only
.global expm1f
expm1f:
    .word 0xE3A0F000 @ unsafe class: slot only
.global frexpf
frexpf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ilogb
ilogb:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ilogbf
ilogbf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ldexpf
ldexpf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global logf
logf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log10f
log10f:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log1p
log1p:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log1pf
log1pf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log2
log2:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log2f
log2f:
    .word 0xE3A0F000 @ unsafe class: slot only
.global logb
logb:
    .word 0xE3A0F000 @ unsafe class: slot only
.global logbf
logbf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global modff
modff:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmodf
fmodf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global scalbn
scalbn:
    .word 0xE3A0F000 @ unsafe class: slot only
.global scalbnf
scalbnf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global scalbln
scalbln:
    .word 0xE3A0F000 @ unsafe class: slot only
.global scalblnf
scalblnf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cbrt
cbrt:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cbrtf
cbrtf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global powf
powf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sqrtf
sqrtf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global erf
erf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global erff
erff:
    .word 0xE3A0F000 @ unsafe class: slot only
.global erfc
erfc:
    .word 0xE3A0F000 @ unsafe class: slot only
.global erfcf
erfcf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lgamma
lgamma:
    .word 0xE3A0F000 @ unsafe class: slot only
.global lgammaf
lgammaf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tgamma
tgamma:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tgammaf
tgammaf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nexttoward
nexttoward:
    .word 0xE3A0F000 @ unsafe class: slot only
.global nexttowardf
nexttowardf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmaf
fmaf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global isblank
isblank:
    .word 0xE3A0F000
.global strtof
strtof:
    .word 0xE3A0F000 @ unsafe class: slot only
.global copysign
copysign:
    .word 0xE3A0F000 @ unsafe class: slot only
.global copysignf
copysignf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fma
fma:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remquo
remquo:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remquof
remquof:
    .word 0xE3A0F000 @ unsafe class: slot only
.global llrint
llrint:
    .word 0xE3A0F000 @ unsafe class: slot only
.global llrintf
llrintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global llround
llround:
    .word 0xE3A0F000 @ unsafe class: slot only
.global llroundf
llroundf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global _cxd_mul
_cxd_mul:
    .word 0xE3A0F000
.global _cxf_mul
_cxf_mul:
    .word 0xE3A0F000
.global _cxd_div
_cxd_div:
    .word 0xE3A0F000
.global _cxf_div
_cxf_div:
    .word 0xE3A0F000
.global _cxd_rdv
_cxd_rdv:
    .word 0xE3A0F000
.global _cxf_rdv
_cxf_rdv:
    .word 0xE3A0F000
.global cacos
cacos:
    .word 0xE3A0F000
.global cacosf
cacosf:
    .word 0xE3A0F000
.global casin
casin:
    .word 0xE3A0F000
.global casinf
casinf:
    .word 0xE3A0F000
.global catan
catan:
    .word 0xE3A0F000
.global catanf
catanf:
    .word 0xE3A0F000
.global ccos
ccos:
    .word 0xE3A0F000
.global ccosf
ccosf:
    .word 0xE3A0F000
.global csin
csin:
    .word 0xE3A0F000
.global csinf
csinf:
    .word 0xE3A0F000
.global ctan
ctan:
    .word 0xE3A0F000
.global ctanf
ctanf:
    .word 0xE3A0F000
.global cacosh
cacosh:
    .word 0xE3A0F000
.global cacoshf
cacoshf:
    .word 0xE3A0F000
.global casinh
casinh:
    .word 0xE3A0F000
.global casinhf
casinhf:
    .word 0xE3A0F000
.global catanh
catanh:
    .word 0xE3A0F000
.global catanhf
catanhf:
    .word 0xE3A0F000
.global ccosh
ccosh:
    .word 0xE3A0F000
.global ccoshf
ccoshf:
    .word 0xE3A0F000
.global csinh
csinh:
    .word 0xE3A0F000
.global csinhf
csinhf:
    .word 0xE3A0F000
.global ctanh
ctanh:
    .word 0xE3A0F000
.global ctanhf
ctanhf:
    .word 0xE3A0F000
.global cexp
cexp:
    .word 0xE3A0F000
.global cexpf
cexpf:
    .word 0xE3A0F000
.global clog
clog:
    .word 0xE3A0F000
.global clogf
clogf:
    .word 0xE3A0F000
.global cabs
cabs:
    .word 0xE3A0F000
.global cabsf
cabsf:
    .word 0xE3A0F000
.global cpow
cpow:
    .word 0xE3A0F000
.global cpowf
cpowf:
    .word 0xE3A0F000
.global csqrt
csqrt:
    .word 0xE3A0F000
.global csqrtf
csqrtf:
    .word 0xE3A0F000
.global carg
carg:
    .word 0xE3A0F000
.global cargf
cargf:
    .word 0xE3A0F000
.global cimag
cimag:
    .word 0xE3A0F000
.global cimagf
cimagf:
    .word 0xE3A0F000
.global conj
conj:
    .word 0xE3A0F000
.global conjf
conjf:
    .word 0xE3A0F000
.global cproj
cproj:
    .word 0xE3A0F000
.global cprojf
cprojf:
    .word 0xE3A0F000
.global creal
creal:
    .word 0xE3A0F000
.global crealf
crealf:
    .word 0xE3A0F000
.global _fgetpos64
_fgetpos64:
    .word 0xE3A0F000
.global _fopen64
_fopen64:
    .word 0xE3A0F000
.global _freopen64
_freopen64:
    .word 0xE3A0F000
.global _fseeko64
_fseeko64:
    .word 0xE3A0F000
.global _fsetpos64
_fsetpos64:
    .word 0xE3A0F000
.global _ftello64
_ftello64:
    .word 0xE3A0F000
.global _tmpfile64
_tmpfile64:
    .word 0xE3A0F000
.global aligned_alloc
aligned_alloc:
    .word 0xE3A0F000
.global at_quick_exit
at_quick_exit:
    .word 0xE3A0F000
.global quick_exit
quick_exit:
    .word 0xE3A0F000
.global timespec_get
timespec_get:
    .word 0xE3A0F000
.global coshf
coshf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sinhf
sinhf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tanhf
tanhf:
    .word 0xE3A0F000 @ unsafe class: slot only
_clib5_end:

