/* RISC OS Territory SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Territory_Alphabet (SWI &43052). See PRM 3-829. */
int Territory_Alphabet(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43052" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_AlphabetIdentifier (SWI &43053). See PRM 3-830. */
int Territory_AlphabetIdentifier(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43053" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_AlphabetNumberToName (SWI &43045). See PRM 3-806. */
void Territory_AlphabetNumberToName(int alphabet, void *buffer, void *length)
{
    register int reg0 __asm("r0") = alphabet;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x43045" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_CharacterPropertyTable (SWI &43056). See PRM 3-834. */
int Territory_CharacterPropertyTable(int territory, void *code)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = code;
    __asm__ volatile("swi 0x43056" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_Collate (SWI &4305D). See PRM 3-842. */
int Territory_Collate(int territory, void *string, void *string2, int flags)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = string2;
    register int reg3 __asm("r3") = flags;
    __asm__ volatile("swi 0x4305D" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Territory_ControlTable (SWI &43059). See PRM 3-838. */
int Territory_ControlTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43059" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_ConvertOrdinalsToTime (SWI &43051). See PRM 3-827. */
void Territory_ConvertOrdinalsToTime(int territory, void *block, void *block2)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = block;
    register void * reg2 __asm("r2") = block2;
    __asm__ volatile("swi 0x43051" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_ConvertStandardDate (SWI &4304D). See PRM 3-819. */
int Territory_ConvertStandardDate(int territory, void *ptr, void *string, void *size)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = string;
    register void * reg3 __asm("r3") = size;
    __asm__ volatile("swi 0x4304D" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Territory_ConvertStandardDateAndTime (SWI &4304C). See PRM 3-817. */
int Territory_ConvertStandardDateAndTime(int territory, void *ptr, void *string, void *size)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = string;
    register void * reg3 __asm("r3") = size;
    __asm__ volatile("swi 0x4304C" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Territory_ConvertStandardTime (SWI &4304E). See PRM 3-821. */
int Territory_ConvertStandardTime(int territory, void *ptr, void *string, void *size)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = string;
    register void * reg3 __asm("r3") = size;
    __asm__ volatile("swi 0x4304E" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Territory_ConvertTextToString (SWI &43075). See PRM 3-812. */
void Territory_ConvertTextToString(void)
{
    __asm__ volatile("swi 0x43075" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_ConvertTimeToOrdinals (SWI &4304F). See PRM 3-823. */
void Territory_ConvertTimeToOrdinals(int territory, void *ptr, void *buffer)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = buffer;
    __asm__ volatile("swi 0x4304F" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_ConvertTimeToUTCOrdinals (SWI &43049). See PRM 3-810. */
void Territory_ConvertTimeToUTCOrdinals(void *ptr, void *buffer)
{
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = buffer;
    __asm__ volatile("swi 0x43049" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* Territory_Deregister (SWI &43042). See PRM 3-803. */
void Territory_Deregister(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43042" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_Exists (SWI &43044). See PRM 3-805. */
void Territory_Exists(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43044" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_LowerCaseTable (SWI &43057). See PRM 3-836. */
int Territory_LowerCaseTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43057" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_NameToNumber (SWI &43060). See PRM 3-849. */
int Territory_NameToNumber(int territory, void *territory2)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = territory2;
    __asm__ volatile("swi 0x43060" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_Number (SWI &43040). See PRM 3-800. */
int Territory_Number(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x43040" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_NumberToName (SWI &43043). See PRM 3-804. */
void Territory_NumberToName(int territory, void *buffer, void *length)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x43043" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_PlainTable (SWI &4305A). See PRM 3-839. */
int Territory_PlainTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x4305A" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_ReadCalendarInformation (SWI &4305F). See PRM 3-847. */
void Territory_ReadCalendarInformation(int territory, void *ptr, void *buffer)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = buffer;
    __asm__ volatile("swi 0x4305F" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_ReadCurrentTimeZone (SWI &43048). See PRM 3-809. */
int Territory_ReadCurrentTimeZone(int *out_offset)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x43048" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_offset) *out_offset = reg1;
    return reg0;
}

/* Territory_ReadTimeZones (SWI &4304A). See PRM 3-814. */
int Territory_ReadTimeZones(int territory, int *out_name, int *out_offset, int *out_offset2)
{
    register int reg0 __asm("r0") = territory;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4304A" : "+r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_offset2) *out_offset2 = reg3;
    if (out_offset) *out_offset = reg2;
    if (out_name) *out_name = reg1;
    return reg0;
}

/* Territory_Register (SWI &43041). See PRM 3-801. */
void Territory_Register(int territory, void *ptr, int territory2)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = territory2;
    __asm__ volatile("swi 0x43041" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Territory_RepresentationTable (SWI &4305C). See PRM 3-841. */
int Territory_RepresentationTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x4305C" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_SelectAlphabet (SWI &43046). See PRM 3-807. */
void Territory_SelectAlphabet(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43046" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_SelectKeyboardHandler (SWI &43054). See PRM 3-831. */
void Territory_SelectKeyboardHandler(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43054" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_SetTime (SWI &43047). See PRM 3-808. */
void Territory_SetTime(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x43047" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Territory_TransformString (SWI &43061). See PRM 3-850. */
int Territory_TransformString(int territory, void *string, void *string2, void *length)
{
    register int reg0 __asm("r0") = territory;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = string2;
    register void * reg3 __asm("r3") = length;
    __asm__ volatile("swi 0x43061" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Territory_UpperCaseTable (SWI &43058). See PRM 3-837. */
int Territory_UpperCaseTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43058" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_ValueTable (SWI &4305B). See PRM 3-840. */
int Territory_ValueTable(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x4305B" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Territory_WriteDirection (SWI &43055). See PRM 3-832. */
int Territory_WriteDirection(int territory)
{
    register int reg0 __asm("r0") = territory;
    __asm__ volatile("swi 0x43055" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}
