/* RISC OS Cache SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Cache_Cacheable (SWI &281). See PRM 4-194. */
int Cache_Cacheable(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x281" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Control (SWI &280). See PRM 4-192. */
int Cache_Control(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x280" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Disruptive (SWI &283). See PRM 4-198. */
int Cache_Disruptive(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x283" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Flush (SWI &284). See PRM 4-200. */
void Cache_Flush(void)
{
    __asm__ volatile("swi 0x284" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Cache_Updateable (SWI &282). See PRM 4-196. */
int Cache_Updateable(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x282" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}
