/* RISC OS ColourPicker SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ColourPicker_CloseDialogue (SWI &47703). See PRM 5a-566. */
void ColourPicker_CloseDialogue(int flags, int handle)
{
    register int reg0 __asm("r0") = flags;
    register int reg1 __asm("r1") = handle;
    __asm__ volatile("swi 0x47703" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_DeregisterModel (SWI &47701). See PRM 5a-561. */
void ColourPicker_DeregisterModel(void)
{
    __asm__ volatile("swi 0x47701" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_HelpReply (SWI &47707). See PRM 5a-572. */
void ColourPicker_HelpReply(int flags, void *block)
{
    register int reg0 __asm("r0") = flags;
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x47707" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_ModelSWI (SWI &47708). See PRM 5a-574. */
void ColourPicker_ModelSWI(void)
{
    __asm__ volatile("swi 0x47708" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_OpenDialogue (SWI &47702). See PRM 5a-563. */
int ColourPicker_OpenDialogue(int flags, void *block)
{
    register int reg0 __asm("r0") = flags;
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x47702" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourPicker_ReadDialogue (SWI &47705). See PRM 5a-569. */
int ColourPicker_ReadDialogue(int flags, int handle, void *block)
{
    register int reg0 __asm("r0") = flags;
    register int reg1 __asm("r1") = handle;
    register void * reg2 __asm("r2") = block;
    __asm__ volatile("swi 0x47705" : "+r"(reg1) : "r"(reg0), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg1;
}

/* ColourPicker_RegisterModel (SWI &47700). See PRM 5a-561. */
void ColourPicker_RegisterModel(void)
{
    __asm__ volatile("swi 0x47700" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_SetColour (SWI &47706). See PRM 5a-571. */
void ColourPicker_SetColour(void)
{
    __asm__ volatile("swi 0x47706" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourPicker_UpdateDialogue (SWI &47704). See PRM 5a-568. */
void ColourPicker_UpdateDialogue(void)
{
    __asm__ volatile("swi 0x47704" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
