/* RISC OS Buffer SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Buffer_Create (SWI &42940). See PRM 4-88. */
void Buffer_Create(void *buffer, void *size, void *handle)
{
    register void * reg0 __asm("r0") = buffer;
    register void * reg1 __asm("r1") = size;
    register void * reg2 __asm("r2") = handle;
    __asm__ volatile("swi 0x42940" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Buffer_Deregister (SWI &42943). See PRM 4-93. */
void Buffer_Deregister(void *handle)
{
    register void * reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x42943" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Buffer_GetInfo (SWI &42947). See PRM 4-99. */
int Buffer_GetInfo(void *handle, int *out_buffer, int *out_offset, int *out_offset2, int *out_buffer2, int *out_count)
{
    register void * reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x42947" : "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : "r"(reg0) : "r12", "lr", "memory");
    if (out_count) *out_count = reg6;
    if (out_buffer2) *out_buffer2 = reg5;
    if (out_offset2) *out_offset2 = reg4;
    if (out_offset) *out_offset = reg3;
    if (out_buffer) *out_buffer = reg2;
    return reg1;
}

/* Buffer_ModifyFlags (SWI &42944). See PRM 4-94. */
int Buffer_ModifyFlags(void *handle, int mask, int mask2, int *out_value)
{
    register void * reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = mask;
    register int reg2 __asm("r2") = mask2;
    __asm__ volatile("swi 0x42944" : "+r"(reg1), "+r"(reg2) : "r"(reg0) : "r3", "r12", "lr", "memory");
    if (out_value) *out_value = reg2;
    return reg1;
}

/* Buffer_Register (SWI &42942). See PRM 4-91. */
void Buffer_Register(void *buffer, void *buffer2, void *buffer3, void *handle)
{
    register void * reg0 __asm("r0") = buffer;
    register void * reg1 __asm("r1") = buffer2;
    register void * reg2 __asm("r2") = buffer3;
    register void * reg3 __asm("r3") = handle;
    __asm__ volatile("swi 0x42942" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* Buffer_Remove (SWI &42941). See PRM 4-90. */
void Buffer_Remove(void *handle)
{
    register void * reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x42941" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Buffer_Threshold (SWI &42948). See PRM 4-101. */
int Buffer_Threshold(void *handle, int threshold)
{
    register void * reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = threshold;
    __asm__ volatile("swi 0x42948" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* Buffer_UnlinkDevice (SWI &42946). See PRM 4-98. */
void Buffer_UnlinkDevice(void *handle)
{
    register void * reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x42946" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}
