/* RISC OS IIC SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* IIC_Control (SWI &240). See PRM 1-979. */
void IIC_Control(void *address, void *block, void *block2)
{
    register void * reg0 __asm("r0") = address;
    register void * reg1 __asm("r1") = block;
    register void * reg2 __asm("r2") = block2;
    __asm__ volatile("swi 0x240" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}
