/* RISC OS BASICTrans SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* BASICTrans_Error (SWI &42C81): Copy translated error string to buffer */
void BASICTrans_Error(int unique, void *buffer)
{
    register int reg0 __asm("r0") = unique;
    register void * reg1 __asm("r1") = buffer;
    __asm__ volatile("swi 0x42C81" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* BASICTrans_HELP (SWI &42C80): Interpret, translate if required, and print HELP messages */
void BASICTrans_HELP(void *ptr, void *ptr2, void *ptr3)
{
    register void * reg0 __asm("r0") = ptr;
    register void * reg1 __asm("r1") = ptr2;
    register void * reg2 __asm("r2") = ptr3;
    __asm__ volatile("swi 0x42C80" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* BASICTrans_Message (SWI &42C82): Translate and print miscellaneous message */
void BASICTrans_Message(int message, int message2)
{
    register int reg0 __asm("r0") = message;
    register int reg1 __asm("r1") = message2;
    __asm__ volatile("swi 0x42C82" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
