/* RISC OS NetFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* NetFS_ConvertDate (SWI &4004B). See PRM 2-364. */
void NetFS_ConvertDate(void *ptr, void *buffer)
{
    register void * reg0 __asm("r0") = ptr;
    register void * reg1 __asm("r1") = buffer;
    __asm__ volatile("swi 0x4004B" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_DoFSOp (SWI &40048). See PRM 2-358. */
int NetFS_DoFSOp(int file, void *buffer, void *count, void *size)
{
    register int reg0 __asm("r0") = file;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = count;
    register void * reg3 __asm("r3") = size;
    __asm__ volatile("swi 0x40048" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* NetFS_EnableCache (SWI &40051). See PRM 2-376. */
void NetFS_EnableCache(void)
{
    __asm__ volatile("swi 0x40051" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_EnumerateFS (SWI &4004A). See PRM 2-362. */
int NetFS_EnumerateFS(int offset, void *buffer, void *size, int count, int *out_count)
{
    register int reg0 __asm("r0") = offset;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = size;
    register int reg3 __asm("r3") = count;
    __asm__ volatile("swi 0x4004A" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_count) *out_count = reg3;
    return reg0;
}

/* NetFS_EnumerateFSContexts (SWI &4004E). See PRM 2-370. */
int NetFS_EnumerateFSContexts(int entry, void *buffer, void *count, int count2, int *out_count)
{
    register int reg0 __asm("r0") = entry;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = count;
    register int reg3 __asm("r3") = count2;
    __asm__ volatile("swi 0x4004E" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_count) *out_count = reg3;
    return reg0;
}

/* NetFS_EnumerateFSList (SWI &40049). See PRM 2-360. */
int NetFS_EnumerateFSList(int offset, void *buffer, void *size, int count, int *out_count)
{
    register int reg0 __asm("r0") = offset;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = size;
    register int reg3 __asm("r3") = count;
    __asm__ volatile("swi 0x40049" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_count) *out_count = reg3;
    return reg0;
}

/* NetFS_ReadCurrentContext (SWI &40044). See PRM 2-354. */
void NetFS_ReadCurrentContext(void)
{
    __asm__ volatile("swi 0x40044" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_ReadFSName (SWI &40042). See PRM 2-352. */
int NetFS_ReadFSName(void *buffer, void *size)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = size;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40042" : "=r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* NetFS_ReadFSNumber (SWI &40040). See PRM 2-350. */
int NetFS_ReadFSNumber(int *out_net)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40040" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_net) *out_net = reg1;
    return reg0;
}

/* NetFS_ReadFSTimeouts (SWI &40046). See PRM 2-356. */
int NetFS_ReadFSTimeouts(int *out_transmit, int *out_machine, int *out_machine2, int *out_receive, int *out_broadcast)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    __asm__ volatile("swi 0x40046" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5) : : "r12", "lr", "memory");
    if (out_broadcast) *out_broadcast = reg5;
    if (out_receive) *out_receive = reg4;
    if (out_machine2) *out_machine2 = reg3;
    if (out_machine) *out_machine = reg2;
    if (out_transmit) *out_transmit = reg1;
    return reg0;
}

/* NetFS_ReadUserId (SWI &4004F). See PRM 2-372. */
void NetFS_ReadUserId(void *buffer, void *count)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = count;
    __asm__ volatile("swi 0x4004F" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* NetFS_SetCurrentContext (SWI &40045). See PRM 2-355. */
void NetFS_SetCurrentContext(void)
{
    __asm__ volatile("swi 0x40045" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_SetFSName (SWI &40043). See PRM 2-353. */
void NetFS_SetFSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    __asm__ volatile("swi 0x40043" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_SetFSNumber (SWI &40041). See PRM 2-351. */
void NetFS_SetFSNumber(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    __asm__ volatile("swi 0x40041" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_UpdateFSList (SWI &4004D). See PRM 2-368. */
void NetFS_UpdateFSList(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    __asm__ volatile("swi 0x4004D" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
