/* RISC OS Wimp SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Wimp_AddMessages (SWI &400F6). See PRM 3-224. */
void Wimp_AddMessages(void *message)
{
    register void * reg0 __asm("r0") = message;
    __asm__ volatile("swi 0x400F6" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_BaseOfSprites (SWI &400EA). See PRM 3-200. */
int Wimp_BaseOfSprites(int *out_sprite_area)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x400EA" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_sprite_area) *out_sprite_area = reg1;
    return reg0;
}

/* Wimp_ClaimFreeMemory (SWI &400EE). See PRM 3-208. */
int Wimp_ClaimFreeMemory(int arg0, int amount, int *out_address)
{
    register int reg0 __asm("r0") = arg0;
    register int reg1 __asm("r1") = amount;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x400EE" : "+r"(reg1), "=r"(reg2) : "r"(reg0) : "r3", "r12", "lr", "memory");
    if (out_address) *out_address = reg2;
    return reg1;
}

/* Wimp_CloseTemplate (SWI &400DA). See PRM 3-166. */
void Wimp_CloseTemplate(void)
{
    __asm__ volatile("swi 0x400DA" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_CloseWindow (SWI &400C6). See PRM 3-111. */
void Wimp_CloseWindow(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400C6" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_CommandWindow (SWI &400EF). See PRM 3-210. */
void Wimp_CommandWindow(int operation)
{
    register int reg0 __asm("r0") = operation;
    __asm__ volatile("swi 0x400EF" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_CreateIcon (SWI &400C2). See PRM 3-93. */
int Wimp_CreateIcon(int icon, void *block)
{
    register int reg0 __asm("r0") = icon;
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400C2" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_CreateMenu (SWI &400D4). See PRM 3-153. */
void Wimp_CreateMenu(void *block, int x, int y)
{
    register void * reg1 __asm("r1") = block;
    register int reg2 __asm("r2") = x;
    register int reg3 __asm("r3") = y;
    __asm__ volatile("swi 0x400D4" : : "r"(reg1), "r"(reg2), "r"(reg3) : "r0", "r12", "lr", "memory");
}

/* Wimp_CreateSubMenu (SWI &400E8). See PRM 3-196. */
void Wimp_CreateSubMenu(void *block, int x, int y)
{
    register void * reg1 __asm("r1") = block;
    register int reg2 __asm("r2") = x;
    register int reg3 __asm("r3") = y;
    __asm__ volatile("swi 0x400E8" : : "r"(reg1), "r"(reg2), "r"(reg3) : "r0", "r12", "lr", "memory");
}

/* Wimp_CreateWindow (SWI &400C1). See PRM 3-87. */
int Wimp_CreateWindow(void *window_block)
{
    register void * reg1 __asm("r1") = window_block;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x400C1" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_DecodeMenu (SWI &400D5). See PRM 3-158. */
void Wimp_DecodeMenu(void *ptr, void *ptr2, void *buffer)
{
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = ptr2;
    register void * reg3 __asm("r3") = buffer;
    __asm__ volatile("swi 0x400D5" : : "r"(reg1), "r"(reg2), "r"(reg3) : "r0", "r12", "lr", "memory");
}

/* Wimp_DeleteIcon (SWI &400C4). See PRM 3-107. */
void Wimp_DeleteIcon(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400C4" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_DeleteWindow (SWI &400C3). See PRM 3-105. */
void Wimp_DeleteWindow(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400C3" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_DragBox (SWI &400D0). See PRM 3-142. */
void Wimp_DragBox(int arg1)
{
    register int reg1 __asm("r1") = arg1;
    __asm__ volatile("swi 0x400D0" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_Extend (SWI &400FB). See PRM 5a-507. */
void Wimp_Extend(void)
{
    __asm__ volatile("swi 0x400FB" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetCaretPosition (SWI &400D3). See PRM 3-151. */
void Wimp_GetCaretPosition(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400D3" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetIconState (SWI &400CE). See PRM 3-138. */
void Wimp_GetIconState(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400CE" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetMenuState (SWI &400F4). See PRM 3-220. */
void Wimp_GetMenuState(int arg0, void *buffer, int window, int icon)
{
    register int reg0 __asm("r0") = arg0;
    register void * reg1 __asm("r1") = buffer;
    register int reg2 __asm("r2") = window;
    register int reg3 __asm("r3") = icon;
    __asm__ volatile("swi 0x400F4" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* Wimp_GetPointerInfo (SWI &400CF). See PRM 3-140. */
void Wimp_GetPointerInfo(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400CF" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetRectangle (SWI &400CA). See PRM 3-130. */
int Wimp_GetRectangle(void *block)
{
    register void * reg1 __asm("r1") = block;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x400CA" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_GetWindowInfo (SWI &400CC). See PRM 3-134. */
void Wimp_GetWindowInfo(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400CC" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetWindowOutline (SWI &400E0). See PRM 3-179. */
void Wimp_GetWindowOutline(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400E0" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_GetWindowState (SWI &400CB). See PRM 3-132. */
void Wimp_GetWindowState(void)
{
    __asm__ volatile("swi 0x400CB" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_OpenTemplate (SWI &400D9). See PRM 3-165. */
void Wimp_OpenTemplate(void *ptr)
{
    register void * reg1 __asm("r1") = ptr;
    __asm__ volatile("swi 0x400D9" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_OpenWindow (SWI &400C5). See PRM 3-109. */
void Wimp_OpenWindow(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400C5" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_PlotIcon (SWI &400E2). See PRM 3-183. */
void Wimp_PlotIcon(void *icon_block)
{
    register void * reg1 __asm("r1") = icon_block;
    __asm__ volatile("swi 0x400E2" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_Poll (SWI &400C7). See PRM 3-112. */
int Wimp_Poll(int mask, void *block, void *ptr)
{
    register int reg0 __asm("r0") = mask;
    register void * reg1 __asm("r1") = block;
    register void * reg3 __asm("r3") = ptr;
    __asm__ volatile("swi 0x400C7" : "+r"(reg0) : "r"(reg1), "r"(reg3) : "r2", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_ProcessKey (SWI &400DC). See PRM 3-170. */
void Wimp_ProcessKey(int character)
{
    register int reg0 __asm("r0") = character;
    __asm__ volatile("swi 0x400DC" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_ReadPalette (SWI &400E5). See PRM 3-189. */
void Wimp_ReadPalette(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400E5" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_ReadPixTrans (SWI &400ED). See PRM 3-206. */
void Wimp_ReadPixTrans(void)
{
    __asm__ volatile("swi 0x400ED" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_ReadSysInfo (SWI &400F2). See PRM 3-216. */
int Wimp_ReadSysInfo(int information)
{
    register int reg0 __asm("r0") = information;
    __asm__ volatile("swi 0x400F2" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_RedrawWindow (SWI &400C8). See PRM 3-126. */
int Wimp_RedrawWindow(void *block)
{
    register void * reg1 __asm("r1") = block;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x400C8" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_RegisterFilter (SWI &400F5). See PRM 3-222. */
void Wimp_RegisterFilter(void)
{
    __asm__ volatile("swi 0x400F5" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_RemoveMessages (SWI &400F7). See PRM 3-225. */
void Wimp_RemoveMessages(void *message)
{
    register void * reg0 __asm("r0") = message;
    __asm__ volatile("swi 0x400F7" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_ReportError (SWI &400DF). See PRM 3-176. */
int Wimp_ReportError(void *block, int flags, void *ptr)
{
    register void * reg0 __asm("r0") = block;
    register int reg1 __asm("r1") = flags;
    register void * reg2 __asm("r2") = ptr;
    __asm__ volatile("swi 0x400DF" : "+r"(reg1) : "r"(reg0), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg1;
}

/* Wimp_ResizeIcon (SWI &400FC). See PRM 5a-510. */
void Wimp_ResizeIcon(void)
{
    __asm__ volatile("swi 0x400FC" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SendMessage (SWI &400E7). See PRM 3-193. */
int Wimp_SendMessage(int event, void *block, int task, int icon)
{
    register int reg0 __asm("r0") = event;
    register void * reg1 __asm("r1") = block;
    register int reg2 __asm("r2") = task;
    register int reg3 __asm("r3") = icon;
    __asm__ volatile("swi 0x400E7" : "+r"(reg2) : "r"(reg0), "r"(reg1), "r"(reg3) : "r12", "lr", "memory");
    return reg2;
}

/* Wimp_SetColour (SWI &400E6). See PRM 3-191. */
void Wimp_SetColour(int colour)
{
    register int reg0 __asm("r0") = colour;
    __asm__ volatile("swi 0x400E6" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SetExtent (SWI &400D7). See PRM 3-161. */
void Wimp_SetExtent(int window, void *block)
{
    register int reg0 __asm("r0") = window;
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400D7" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SetFontColours (SWI &400F3). See PRM 3-218. */
void Wimp_SetFontColours(int colour, int colour2)
{
    register int reg1 __asm("r1") = colour;
    register int reg2 __asm("r2") = colour2;
    __asm__ volatile("swi 0x400F3" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* Wimp_SetIconState (SWI &400CD). See PRM 3-136. */
void Wimp_SetIconState(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400CD" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SetMode (SWI &400E3). See PRM 3-185. */
void Wimp_SetMode(int mode)
{
    register int reg0 __asm("r0") = mode;
    __asm__ volatile("swi 0x400E3" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SetPalette (SWI &400E4). See PRM 3-187. */
void Wimp_SetPalette(void *block)
{
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x400E4" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SetWatchdogState (SWI &400FA). See PRM 5a-506. */
void Wimp_SetWatchdogState(int state, int code)
{
    register int reg0 __asm("r0") = state;
    register int reg1 __asm("r1") = code;
    __asm__ volatile("swi 0x400FA" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_SlotSize (SWI &400EC). See PRM 3-203. */
int Wimp_SlotSize(int size, int size2, int *out_size, int *out_size2)
{
    register int reg0 __asm("r0") = size;
    register int reg1 __asm("r1") = size2;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x400EC" : "+r"(reg0), "+r"(reg1), "=r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_size2) *out_size2 = reg2;
    if (out_size) *out_size = reg1;
    return reg0;
}

/* Wimp_StartTask (SWI &400DE). See PRM 3-174. */
void Wimp_StartTask(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x400DE" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_TextColour (SWI &400F0). See PRM 3-212. */
void Wimp_TextColour(int colour)
{
    register int reg0 __asm("r0") = colour;
    __asm__ volatile("swi 0x400F0" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Wimp_UpdateWindow (SWI &400C9). See PRM 3-128. */
int Wimp_UpdateWindow(void *block)
{
    register void * reg1 __asm("r1") = block;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x400C9" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Wimp_WhichIcon (SWI &400D6). See PRM 3-159. */
void Wimp_WhichIcon(int window, void *block, int mask, int arg3)
{
    register int reg0 __asm("r0") = window;
    register void * reg1 __asm("r1") = block;
    register int reg2 __asm("r2") = mask;
    register int reg3 __asm("r3") = arg3;
    __asm__ volatile("swi 0x400D6" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}
