/* RISC OS Cache SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Cache_Cacheable (SWI &281): Controls which areas of memory may be cached */
int Cache_Cacheable(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x281" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Control (SWI &280): Turns the cache on or off */
int Cache_Control(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x280" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Disruptive (SWI &283): Controls which areas of memory cause automatic flushing of the cache on a write */
int Cache_Disruptive(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x283" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Cache_Flush (SWI &284): Flushes the cache */
void Cache_Flush(void)
{
    __asm__ volatile("swi 0x284" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Cache_Updateable (SWI &282): Controls which areas of memory will be automatically updated in the cache */
int Cache_Updateable(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x282" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}
