/* RISC OS Portable SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Portable_Control (SWI &42FC1). See PRM 4-210. */
int Portable_Control(int mask, int mask2, int *out_new)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x42FC1" : "+r"(reg0), "+r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_new) *out_new = reg1;
    return reg0;
}

/* Portable_ReadBMUVariable (SWI &42FC2). See PRM 4-212. */
int Portable_ReadBMUVariable(int bmu)
{
    register int reg0 __asm("r0") = bmu;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x42FC2" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* Portable_Speed (SWI &42FC0). See PRM 4-208. */
int Portable_Speed(int mask, int mask2, int *out_new)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x42FC0" : "+r"(reg0), "+r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_new) *out_new = reg1;
    return reg0;
}

/* Portable_WriteBMUVariable (SWI &42FC3). See PRM 4-214. */
void Portable_WriteBMUVariable(int bmu, int value)
{
    register int reg0 __asm("r0") = bmu;
    register int reg1 __asm("r1") = value;
    __asm__ volatile("swi 0x42FC3" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
