/* RISC OS Joystick SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Joystick_CalibrateTopRight (SWI &43F41): Calibrates analogue joysticks to return the full range of values */
void Joystick_CalibrateTopRight(void)
{
    __asm__ volatile("swi 0x43F41" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
