/* RISC OS PDriver SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* PDriver_AbortJob (SWI &80149): End a print job without any further output */
void PDriver_AbortJob(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x80149" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CancelJob (SWI &8014E): Stops the print job associated with a file handle from printing */
void PDriver_CancelJob(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x8014E" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CancelJobWithError (SWI &80152): Cancels a print job – future attempts to output to it generate an error */
void PDriver_CancelJobWithError(int handle, void *ptr)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = ptr;
    __asm__ volatile("swi 0x80152" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CheckFeatures (SWI &80142): Check the features of a printer */
void PDriver_CheckFeatures(int mask, int value)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = value;
    __asm__ volatile("swi 0x80142" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CurrentJob (SWI &80146): Get the file handle of the current job */
int PDriver_CurrentJob(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x80146" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_DeclareFont (SWI &80155): Declares the fonts that will be used in a document */
void PDriver_DeclareFont(int handle, void *ptr, int flags)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = flags;
    __asm__ volatile("swi 0x80155" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* PDriver_DrawPage (SWI &8014C): Called to draw the page after all rectangles specified */
int PDriver_DrawPage(int r0, void *ptr, int r2, void *string, int *out_r2)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = r2;
    register void * reg3 __asm("r3") = string;
    __asm__ volatile("swi 0x8014C" : "+r"(reg0), "+r"(reg2) : "r"(reg1), "r"(reg3) : "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    return reg0;
}

/* PDriver_EndJob (SWI &80148): End a print job normally */
void PDriver_EndJob(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x80148" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_EnumerateDrivers (SWI &80159): Enumerates all drivers within the system */
int PDriver_EnumerateDrivers(int handle, int *out_r1)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x80159" : "+r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* PDriver_EnumerateJobs (SWI &80150): List existing print jobs */
int PDriver_EnumerateJobs(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x80150" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_FontSWI (SWI &80147): This call is part of the internal interface between the font system and printer drivers */
void PDriver_FontSWI(void)
{
    __asm__ volatile("swi 0x80147" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_GetRectangle (SWI &8014D): Get the next print rectangle */
int PDriver_GetRectangle(void *ptr, int *out_r2)
{
    register void * reg1 __asm("r1") = ptr;
    register int reg0 __asm("r0");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x8014D" : "=r"(reg0), "=r"(reg2) : "r"(reg1) : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    return reg0;
}

/* PDriver_Info (SWI &80140): Get information on the printer driver */
int PDriver_Info(int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5, int *out_r6, int *out_r7)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    register int reg7 __asm("r7");
    __asm__ volatile("swi 0x80140" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7) : : "r12", "lr", "memory");
    if (out_r7) *out_r7 = reg7;
    if (out_r6) *out_r6 = reg6;
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* PDriver_PageSize (SWI &80143): Find how large the paper and print area is */
int PDriver_PageSize(int *out_r2, int *out_r3, int *out_r4, int *out_r5, int *out_r6)
{
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x80143" : "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r0", "r12", "lr", "memory");
    if (out_r6) *out_r6 = reg6;
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    return reg1;
}

/* PDriver_RemoveDriver (SWI &80157): Deregisters a printer driver with the PDriver sharer module */
void PDriver_RemoveDriver(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x80157" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_Reset (SWI &8014A): Abort all print jobs */
void PDriver_Reset(void)
{
    __asm__ volatile("swi 0x8014A" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_ScreenDump (SWI &8014F): Output a screen dump to the printer */
void PDriver_ScreenDump(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x8014F" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_SelectDriver (SWI &80158): Selects the specified driver */
int PDriver_SelectDriver(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x80158" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SelectIllustration (SWI &80153): Makes the given print job the current one, and treats it as an illustration */
int PDriver_SelectIllustration(int handle, void *string)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x80153" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SelectJob (SWI &80145): Make a given print job the current one */
int PDriver_SelectJob(int handle, void *string)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x80145" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SetPrinter (SWI &80151): This call is used to set options specific to a particular printer driver. It is a private */
void PDriver_SetPrinter(void)
{
    __asm__ volatile("swi 0x80151" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
