/* RISC OS NetPrint SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* NetPrint_BindPSName (SWI &40206): Converts a printer server’s name to its address, providing it is free */
int NetPrint_BindPSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40206" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* NetPrint_ConvertStatusToString (SWI &40208): *Configure PS sets the configured default network printer server */
void NetPrint_ConvertStatusToString(void)
{
    __asm__ volatile("swi 0x40208" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetPrint_ListServers (SWI &40207): Returns the names of all printer servers */
int NetPrint_ListServers(int r0, void *buffer, void *buffer2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x40207" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg0;
}

/* NetPrint_ReadPSName (SWI &40202): Reads the name of your current printer server */
int NetPrint_ReadPSName(void *buffer, void *buffer2)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40202" : "=r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* NetPrint_ReadPSNumber (SWI &40200): Returns the full station number of your current printer server */
int NetPrint_ReadPSNumber(int *out_r1)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40200" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* NetPrint_ReadPSTimeouts (SWI &40204): Reads the current values for timeouts used by NetPrint */
int NetPrint_ReadPSTimeouts(int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    __asm__ volatile("swi 0x40204" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5) : : "r12", "lr", "memory");
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* NetPrint_SetPSName (SWI &40203): Sets by name the printer server used as your current one */
void NetPrint_SetPSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    __asm__ volatile("swi 0x40203" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetPrint_SetPSNumber (SWI &40201): Sets the full station number used as the current printer server */
void NetPrint_SetPSNumber(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    __asm__ volatile("swi 0x40201" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
