/* RISC OS TaskManager SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* TaskManager_EnumerateTasks (SWI &42681): Enumerates all the currently active tasks */
int TaskManager_EnumerateTasks(int value, void *buffer, void *length)
{
    register int reg0 __asm("r0") = value;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x42681" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* TaskManager_Shutdown (SWI &42682): Initiates a desktop shutdown */
void TaskManager_Shutdown(int flags)
{
    register int reg0 __asm("r0") = flags;
    __asm__ volatile("swi 0x42682" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* TaskManager_TaskNameFromHandle (SWI &42680): Finds the name of a task */
int TaskManager_TaskNameFromHandle(int task)
{
    register int reg0 __asm("r0") = task;
    __asm__ volatile("swi 0x42680" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}
