/* RISC OS ADFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ADFS_ControllerType (SWI &40248): Returns the controller type of a drive */
void ADFS_ControllerType(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40248" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_DescribeDisc (SWI &40245): Calls FileCore_DescribeDisc */
void ADFS_DescribeDisc(void)
{
    __asm__ volatile("swi 0x40245" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_DiscOp (SWI &40240): Calls FileCore_DiscOp */
void ADFS_DiscOp(void)
{
    __asm__ volatile("swi 0x40240" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_Drives (SWI &40242): Calls FileCore_Drives */
void ADFS_Drives(void)
{
    __asm__ volatile("swi 0x40242" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_ECCSAndRetries (SWI &40250): For internal use only */
void ADFS_ECCSAndRetries(void)
{
    __asm__ volatile("swi 0x40250" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FlpProcessDCB (SWI &40247): For internal use only */
void ADFS_FlpProcessDCB(void)
{
    __asm__ volatile("swi 0x40247" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FreeSpace (SWI &40243): Calls FileCore_FreeSpace */
void ADFS_FreeSpace(void)
{
    __asm__ volatile("swi 0x40243" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FreeSpace64 (SWI &40252): Calls FileCore_FreeSpace64 */
void ADFS_FreeSpace64(void)
{
    __asm__ volatile("swi 0x40252" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_LockIDE (SWI &40251): Locks/unlocks the IDE bus */
void ADFS_LockIDE(int flags)
{
    register int reg0 __asm("r0") = flags;
    __asm__ volatile("swi 0x40251" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_MiscOp (SWI &4024C): Calls FileCore_MiscOp */
void ADFS_MiscOp(void)
{
    __asm__ volatile("swi 0x4024C" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_Retries (SWI &40244): Sets the number of retries used for various operations */
int ADFS_Retries(int mask, int value, int *out_r2, int *out_r3)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = value;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x40244" : "+r"(reg1), "=r"(reg2), "=r"(reg3) : "r"(reg0) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    return reg1;
}

/* ADFS_SectorDiscOp (SWI &4024D): Calls FileCore_SectorOp */
void ADFS_SectorDiscOp(void)
{
    __asm__ volatile("swi 0x4024D" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_VetFormat (SWI &40246): Vets a disc format structure for achievability with the available hardware */
void ADFS_VetFormat(void *ptr, int r1)
{
    register void * reg0 __asm("r0") = ptr;
    register int reg1 __asm("r1") = r1;
    __asm__ volatile("swi 0x40246" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
