/* RISC OS OS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* OS_AddCallBack (SWI &54). See PRM 1-326. */
void OS_AddCallBack(void *address, int value)
{
    register void * reg0 __asm("r0") = address;
    register int reg1 __asm("r1") = value;
    __asm__ volatile("swi 0x54" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_AddToVector (SWI &47). See PRM 1-72. */
void OS_AddToVector(int vector, void *address, int value)
{
    register int reg0 __asm("r0") = vector;
    register void * reg1 __asm("r1") = address;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x47" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_BGet (SWI &A). See PRM 2-63. */
int OS_BGet(int file)
{
    register int reg1 __asm("r1") = file;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0xA" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_BPut (SWI &B). See PRM 2-65. */
void OS_BPut(int byte, int file)
{
    register int reg0 __asm("r0") = byte;
    register int reg1 __asm("r1") = file;
    __asm__ volatile("swi 0xB" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_BinaryToDecimal (SWI &28). See PRM 1-470. */
int OS_BinaryToDecimal(int signed_, void *buffer, int length)
{
    register int reg0 __asm("r0") = signed_;
    register void * reg1 __asm("r1") = buffer;
    register int reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x28" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* OS_BreakCtrl (SWI &18). See PRM 1-312. */
void OS_BreakCtrl(void *block, void *handle)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = handle;
    __asm__ volatile("swi 0x18" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_BreakPt (SWI &17). See PRM 1-311. */
void OS_BreakPt(void)
{
    __asm__ volatile("swi 0x17" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_Byte (SWI &6). See PRM 1-54. */
int OS_Byte(int os_byte, int arg1)
{
    register int reg0 __asm("r0") = os_byte;
    register int reg1 __asm("r1") = arg1;
    __asm__ volatile("swi 0x6" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* OS_CLI (SWI &5). See PRM 1-963. */
void OS_CLI(void *string)
{
    register void * reg0 __asm("r0") = string;
    __asm__ volatile("swi 0x5" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_CRC (SWI &5B). See PRM 1-977. */
int OS_CRC(int value, void *block, void *block2, int increment)
{
    register int reg0 __asm("r0") = value;
    register void * reg1 __asm("r1") = block;
    register void * reg2 __asm("r2") = block2;
    register int reg3 __asm("r3") = increment;
    __asm__ volatile("swi 0x5B" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* OS_CallAfter (SWI &3B). See PRM 1-443. */
void OS_CallAfter(int time, void *address, int value)
{
    register int reg0 __asm("r0") = time;
    register void * reg1 __asm("r1") = address;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x3B" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_CallBack (SWI &15). See PRM 1-309. */
void OS_CallBack(void *block, void *handle)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = handle;
    __asm__ volatile("swi 0x15" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_CallEvery (SWI &3C). See PRM 1-445. */
void OS_CallEvery(int delay, void *address, int value)
{
    register int reg0 __asm("r0") = delay;
    register void * reg1 __asm("r1") = address;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x3C" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ChangeDynamicArea (SWI &2A). See PRM 1-386. */
int OS_ChangeDynamicArea(int area, int amount)
{
    register int reg0 __asm("r0") = area;
    register int reg1 __asm("r1") = amount;
    __asm__ volatile("swi 0x2A" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* OS_ChangeEnvironment (SWI &40). See PRM 1-322. */
int OS_ChangeEnvironment(int handle, void *handle2, int handle3, void *buffer)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = handle2;
    register int reg2 __asm("r2") = handle3;
    register void * reg3 __asm("r3") = buffer;
    __asm__ volatile("swi 0x40" : "+r"(reg2) : "r"(reg0), "r"(reg1), "r"(reg3) : "r12", "lr", "memory");
    return reg2;
}

/* OS_ChangeRedirection (SWI &5E). See PRM 1-966. */
int OS_ChangeRedirection(int arg0, int string)
{
    register int reg0 __asm("r0") = arg0;
    register int reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x5E" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* OS_ChangedBox (SWI &5A). See PRM 1-754. */
int OS_ChangedBox(int arg0, int *out_block)
{
    register int reg0 __asm("r0") = arg0;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x5A" : "+r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_block) *out_block = reg1;
    return reg0;
}

/* OS_CheckModeValid (SWI &3F). See PRM 1-744. */
int OS_CheckModeValid(int mode)
{
    register int reg0 __asm("r0") = mode;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x3F" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* OS_Claim (SWI &1F). See PRM 1-66. */
void OS_Claim(int vector, void *address, int value)
{
    register int reg0 __asm("r0") = vector;
    register void * reg1 __asm("r1") = address;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x1F" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ClaimScreenMemory (SWI &41). See PRM 1-390. */
int OS_ClaimScreenMemory(int arg0, int length, int *out_address)
{
    register int reg0 __asm("r0") = arg0;
    register int reg1 __asm("r1") = length;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x41" : "+r"(reg1), "=r"(reg2) : "r"(reg0) : "r3", "r12", "lr", "memory");
    if (out_address) *out_address = reg2;
    return reg1;
}

/* OS_Confirm (SWI &59). See PRM 1-975. */
int OS_Confirm(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x59" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_Control (SWI &F). See PRM 1-301. */
void OS_Control(void *handle, void *buffer, void *handle2, void *handle3)
{
    register void * reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = handle2;
    register void * reg3 __asm("r3") = handle3;
    __asm__ volatile("swi 0xF" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* OS_ConvertDateAndTime (SWI &C1). See PRM 1-451. */
void OS_ConvertDateAndTime(void *block, void *string, void *size, void *string2)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = size;
    register void * reg3 __asm("r3") = string2;
    __asm__ volatile("swi 0xC1" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* OS_ConvertFileSize (SWI &EC). See PRM 1-494. */
int OS_ConvertFileSize(int size, void *buffer, void *length)
{
    register int reg0 __asm("r0") = size;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0xEC" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_ConvertFixedFileSize (SWI &EB). See PRM 1-492. */
int OS_ConvertFixedFileSize(int size, void *buffer, void *length)
{
    register int reg0 __asm("r0") = size;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0xEB" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_ConvertFixedNetStation (SWI &E9). See PRM 1-488. */
void OS_ConvertFixedNetStation(void *block, void *string, void *size)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = size;
    __asm__ volatile("swi 0xE9" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ConvertNetStation (SWI &EA). See PRM 1-490. */
void OS_ConvertNetStation(void *block, void *string, void *size)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = size;
    __asm__ volatile("swi 0xEA" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ConvertStandardDateAndTime (SWI &C0). See PRM 1-449. */
void OS_ConvertStandardDateAndTime(void *block, void *string, void *size)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = size;
    __asm__ volatile("swi 0xC0" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_DelinkApplication (SWI &4D). See PRM 1-74. */
void OS_DelinkApplication(void *buffer, void *size)
{
    register void * reg0 __asm("r0") = buffer;
    register void * reg1 __asm("r1") = size;
    __asm__ volatile("swi 0x4D" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_EnterOS (SWI &16). See PRM 1-141. */
int OS_EnterOS(int arg0, int event)
{
    register int reg0 __asm("r0") = arg0;
    register int reg1 __asm("r1") = event;
    __asm__ volatile("swi 0x16" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* OS_EvaluateExpression (SWI &2D). See PRM 1-472. */
void OS_EvaluateExpression(void *string, void *buffer, void *length)
{
    register void * reg0 __asm("r0") = string;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x2D" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_Exit (SWI &11). See PRM 1-305. */
void OS_Exit(void *buffer, int abex, int return_)
{
    register void * reg0 __asm("r0") = buffer;
    register int reg1 __asm("r1") = abex;
    register int reg2 __asm("r2") = return_;
    __asm__ volatile("swi 0x11" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ExitAndDie (SWI &50). See PRM 1-325. */
void OS_ExitAndDie(void *buffer, int abex, int return_, void *module)
{
    register void * reg0 __asm("r0") = buffer;
    register int reg1 __asm("r1") = abex;
    register int reg2 __asm("r2") = return_;
    register void * reg3 __asm("r3") = module;
    __asm__ volatile("swi 0x50" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* OS_GSInit (SWI &25). See PRM 1-464. */
int OS_GSInit(void *string, int flags, int *out_value)
{
    register void * reg0 __asm("r0") = string;
    register int reg2 __asm("r2") = flags;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x25" : "+r"(reg2), "=r"(reg1) : "r"(reg0) : "r3", "r12", "lr", "memory");
    if (out_value) *out_value = reg2;
    return reg1;
}

/* OS_GSRead (SWI &26). See PRM 1-466. */
int OS_GSRead(int arg0, int arg2, int *out_next, int *out_string)
{
    register int reg0 __asm("r0") = arg0;
    register int reg2 __asm("r2") = arg2;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x26" : "+r"(reg0), "+r"(reg2), "=r"(reg1) : : "r3", "r12", "lr", "memory");
    if (out_string) *out_string = reg2;
    if (out_next) *out_next = reg1;
    return reg0;
}

/* OS_GSTrans (SWI &27). See PRM 1-468. */
void OS_GSTrans(void *string, void *buffer, void *size)
{
    register void * reg0 __asm("r0") = string;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = size;
    __asm__ volatile("swi 0x27" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_GenerateError (SWI &2B). See PRM 1-45. */
void OS_GenerateError(void *block)
{
    register void * reg0 __asm("r0") = block;
    __asm__ volatile("swi 0x2B" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_GetEnv (SWI &10). See PRM 1-303. */
int OS_GetEnv(int *out_address, int *out_ptr)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x10" : "=r"(reg0), "=r"(reg1), "=r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_ptr) *out_ptr = reg2;
    if (out_address) *out_address = reg1;
    return reg0;
}

/* OS_InstallKeyHandler (SWI &3E). See PRM 1-948. */
void OS_InstallKeyHandler(void)
{
    __asm__ volatile("swi 0x3E" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_IntOff (SWI &14). See PRM 1-140. */
void OS_IntOff(void)
{
    __asm__ volatile("swi 0x14" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_IntOn (SWI &13). See PRM 1-139. */
void OS_IntOn(void)
{
    __asm__ volatile("swi 0x13" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_Mouse (SWI &1C). See PRM 1-728. */
int OS_Mouse(int *out_y, int *out_mouse, int *out_time)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x1C" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_time) *out_time = reg3;
    if (out_mouse) *out_mouse = reg2;
    if (out_y) *out_y = reg1;
    return reg0;
}

/* OS_Plot (SWI &45). See PRM 1-746. */
void OS_Plot(int plot, int x, int y)
{
    register int reg0 __asm("r0") = plot;
    register int reg1 __asm("r1") = x;
    register int reg2 __asm("r2") = y;
    __asm__ volatile("swi 0x45" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_PrettyPrint (SWI &44). See PRM 1-538. */
void OS_PrettyPrint(void *string, void *ptr, void *string2)
{
    register void * reg0 __asm("r0") = string;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = string2;
    __asm__ volatile("swi 0x44" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_PrintChar (SWI &5D). See PRM 1-541. */
void OS_PrintChar(int character)
{
    register int reg0 __asm("r0") = character;
    __asm__ volatile("swi 0x5D" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_ReadArgs (SWI &49). See PRM 1-482. */
int OS_ReadArgs(int value, void *string, void *size)
{
    register int reg0 __asm("r0") = value;
    register void * reg1 __asm("r1") = string;
    register void * reg2 __asm("r2") = size;
    __asm__ volatile("swi 0x49" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_ReadDynamicArea (SWI &5C). See PRM 1-398. */
int OS_ReadDynamicArea(int area, int *out_count)
{
    register int reg0 __asm("r0") = area;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x5C" : "+r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_count) *out_count = reg1;
    return reg0;
}

/* OS_ReadEscapeState (SWI &2C). See PRM 1-945. */
void OS_ReadEscapeState(void)
{
    __asm__ volatile("swi 0x2C" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_ReadMemMapEntries (SWI &52). See PRM 1-394. */
void OS_ReadMemMapEntries(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    __asm__ volatile("swi 0x52" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_ReadMemMapInfo (SWI &51). See PRM 1-393. */
int OS_ReadMemMapInfo(int *out_count)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x51" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_count) *out_count = reg1;
    return reg0;
}

/* OS_ReadModeVariable (SWI &35). See PRM 1-738. */
int OS_ReadModeVariable(int mode, int variable)
{
    register int reg0 __asm("r0") = mode;
    register int reg1 __asm("r1") = variable;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x35" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* OS_ReadMonotonicTime (SWI &42). See PRM 1-448. */
int OS_ReadMonotonicTime(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x42" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_ReadPalette (SWI &2F). See PRM 1-730. */
int OS_ReadPalette(int colour, int colour2, int *out_colour)
{
    register int reg0 __asm("r0") = colour;
    register int reg1 __asm("r1") = colour2;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x2F" : "=r"(reg2), "=r"(reg3) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_colour) *out_colour = reg3;
    return reg2;
}

/* OS_ReadPoint (SWI &32). See PRM 1-736. */
int OS_ReadPoint(int x, int y, int *out_tint, int *out_flags)
{
    register int reg0 __asm("r0") = x;
    register int reg1 __asm("r1") = y;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    __asm__ volatile("swi 0x32" : "=r"(reg2), "=r"(reg3), "=r"(reg4) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_flags) *out_flags = reg4;
    if (out_tint) *out_tint = reg3;
    return reg2;
}

/* OS_ReadRAMFsLimits (SWI &4A). See PRM 1-392. */
int OS_ReadRAMFsLimits(int *out_address)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x4A" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_address) *out_address = reg1;
    return reg0;
}

/* OS_ReadUnsigned (SWI &21). See PRM 1-462. */
int OS_ReadUnsigned(int flags, void *string, int value)
{
    register int reg0 __asm("r0") = flags;
    register void * reg1 __asm("r1") = string;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x21" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* OS_ReadVduVariables (SWI &31). See PRM 1-732. */
void OS_ReadVduVariables(void *block, void *block2)
{
    register void * reg0 __asm("r0") = block;
    register void * reg1 __asm("r1") = block2;
    __asm__ volatile("swi 0x31" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_Release (SWI &20). See PRM 1-68. */
void OS_Release(int vector, void *address, int value)
{
    register int reg0 __asm("r0") = vector;
    register void * reg1 __asm("r1") = address;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x20" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_RemoveCallBack (SWI &5F). See PRM 1-330. */
void OS_RemoveCallBack(void)
{
    __asm__ volatile("swi 0x5F" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_RemoveCursors (SWI &36). See PRM 1-741. */
void OS_RemoveCursors(void)
{
    __asm__ volatile("swi 0x36" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_RemoveTickerEvent (SWI &3D). See PRM 1-447. */
void OS_RemoveTickerEvent(void *address, int value)
{
    register void * reg0 __asm("r0") = address;
    register int reg1 __asm("r1") = value;
    __asm__ volatile("swi 0x3D" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_RestoreCursors (SWI &37). See PRM 1-743. */
void OS_RestoreCursors(void)
{
    __asm__ volatile("swi 0x37" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_SWINumberFromString (SWI &39). See PRM 1-476. */
int OS_SWINumberFromString(void *name)
{
    register void * reg1 __asm("r1") = name;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x39" : "=r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* OS_SWINumberToString (SWI &38). See PRM 1-474. */
void OS_SWINumberToString(int swi, void *buffer, void *length)
{
    register int reg0 __asm("r0") = swi;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x38" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* OS_ServiceCall (SWI &30). See PRM 1-256. */
void OS_ServiceCall(int service)
{
    register int reg1 __asm("r1") = service;
    __asm__ volatile("swi 0x30" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* OS_SetCallBack (SWI &1B). See PRM 1-315. */
void OS_SetCallBack(void)
{
    __asm__ volatile("swi 0x1B" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_SetColour (SWI &61). See PRM 1-756. */
void OS_SetColour(int colour, void *colour2)
{
    register int reg0 __asm("r0") = colour;
    register void * reg1 __asm("r1") = colour2;
    __asm__ volatile("swi 0x61" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_SetECFOrigin (SWI &56). See PRM 1-747. */
void OS_SetECFOrigin(int x, int y)
{
    register int reg0 __asm("r0") = x;
    register int reg1 __asm("r1") = y;
    __asm__ volatile("swi 0x56" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_SetMemMapEntries (SWI &53). See PRM 1-396. */
void OS_SetMemMapEntries(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x53" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_UnusedSWI (SWI &19). See PRM 1-314. */
void OS_UnusedSWI(void *handle)
{
    register void * reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x19" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_UpdateMEMC (SWI &1A). See PRM 1-375. */
int OS_UpdateMEMC(int new, int mask, int *out_mask)
{
    register int reg0 __asm("r0") = new;
    register int reg1 __asm("r1") = mask;
    __asm__ volatile("swi 0x1A" : "+r"(reg0), "+r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_mask) *out_mask = reg1;
    return reg0;
}

/* OS_ValidateAddress (SWI &3A). See PRM 1-388. */
void OS_ValidateAddress(void *address, void *address2)
{
    register void * reg0 __asm("r0") = address;
    register void * reg1 __asm("r1") = address2;
    __asm__ volatile("swi 0x3A" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_Write0 (SWI &2). See PRM 1-30. */
void OS_Write0(void *string)
{
    register void * reg0 __asm("r0") = string;
    __asm__ volatile("swi 0x2" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_WriteC (SWI &0). See PRM 1-517. */
void OS_WriteC(int character)
{
    register int reg0 __asm("r0") = character;
    __asm__ volatile("swi 0x0" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* OS_WriteEnv (SWI &48). See PRM 1-324. */
void OS_WriteEnv(void *string, void *ptr)
{
    register void * reg0 __asm("r0") = string;
    register void * reg1 __asm("r1") = ptr;
    __asm__ volatile("swi 0x48" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_WriteN (SWI &46). See PRM 1-542. */
void OS_WriteN(void *string, int count)
{
    register void * reg0 __asm("r0") = string;
    register int reg1 __asm("r1") = count;
    __asm__ volatile("swi 0x46" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* OS_WriteS (SWI &1). See PRM 1-519. */
void OS_WriteS(void)
{
    __asm__ volatile("swi 0x1" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
