/* RISC OS Econet SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Econet_AbandonAndReadReceive (SWI &40018): Abandons a reception and returns information about it, including the size of data */
int Econet_AbandonAndReadReceive(int handle, int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5, int *out_r6)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40018" : "+r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_r6) *out_r6 = reg6;
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* Econet_AbandonReceive (SWI &40003): Abandons an RxCB */
int Econet_AbandonReceive(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40003" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_AbandonTransmit (SWI &40008): Abandons a TxCB */
int Econet_AbandonTransmit(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40008" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_AllocatePort (SWI &40013): Allocates a unique port number */
int Econet_AllocatePort(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40013" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_ClaimPort (SWI &40015): Claims a specific port number */
void Econet_ClaimPort(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40015" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_DeAllocatePort (SWI &40014): Deallocates a port number that was previously allocated */
void Econet_DeAllocatePort(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40014" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_EnumerateReceive (SWI &40005): Returns the handles of open RxCBs */
void Econet_EnumerateReceive(void *r0)
{
    register void * reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40005" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_EnumerateTransmit (SWI &4001F): Returns the handles of open TxCBs */
void Econet_EnumerateTransmit(void *r0)
{
    register void * reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x4001F" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_ExamineReceive (SWI &40001): Reads the status of an RxCB */
int Econet_ExamineReceive(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40001" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_HardwareAddresses (SWI &40020): Returns the addresses of the Econet hardware and interrupt control registers */
int Econet_HardwareAddresses(int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40020" : "=r"(reg0), "=r"(reg1), "=r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* Econet_InetRxDirect (SWI &4001D): This call is for internal use only. You must not use it in your own code */
void Econet_InetRxDirect(void)
{
    __asm__ volatile("swi 0x4001D" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_NetworkParameters (SWI &40021): *Configure BootNet sets the configured state for whether or not the AUN software is to */
void Econet_NetworkParameters(void)
{
    __asm__ volatile("swi 0x40021" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_NetworkState (SWI &4001A): Returns the state of the underlying transport to a given station */
int Econet_NetworkState(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001A" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_PacketSize (SWI &4001B): Returns the maximum packet size recommended on the underlying transport to a given */
int Econet_PacketSize(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001B" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_PollTransmit (SWI &40007): Reads the status of a TxCB */
int Econet_PollTransmit(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40007" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_PrintBanner (SWI &40010): Prints the string ‘Acorn Econet’ followed by a newline */
void Econet_PrintBanner(void)
{
    __asm__ volatile("swi 0x40010" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_ReadLocalStationAndNet (SWI &4000A): Returns a computer’s station number and net number */
int Econet_ReadLocalStationAndNet(int *out_r1)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x4000A" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* Econet_ReadProtection (SWI &4000D): Reads the current protection word for immediate operations */
int Econet_ReadProtection(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x4000D" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_ReadReceive (SWI &40002): Returns information about a reception, including the size of data */
int Econet_ReadReceive(int handle, int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5, int *out_r6)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40002" : "+r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_r6) *out_r6 = reg6;
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* Econet_ReadStationNumber (SWI &4000F): Extracts a station and/or net number from a supplied string */
int Econet_ReadStationNumber(void *string, int *out_r3)
{
    register void * reg1 __asm("r1") = string;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4000F" : "=r"(reg2), "=r"(reg3) : "r"(reg1) : "r0", "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg2;
}

/* Econet_ReadTransportName (SWI &4001C): Returns the name of the underlying transport to a given station */
int Econet_ReadTransportName(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001C" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_ReadTransportType (SWI &40011): Returns the underlying transport type to a given station */
int Econet_ReadTransportType(int r0, int r1, int r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x40011" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_ReleasePort (SWI &40012): Releases a port number that was previously claimed */
void Econet_ReleasePort(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40012" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_SetProtection (SWI &4000E): Sets or reads the protection word for immediate operations */
int Econet_SetProtection(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x4000E" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_Version (SWI &40019): Returns the version of software for the underlying transport to a given station */
int Econet_Version(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40019" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_WaitForReception (SWI &40004): Polls an RxCB, reads its status, and abandons it */
int Econet_WaitForReception(int handle, int r1, int r2, int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5, int *out_r6)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40004" : "+r"(reg0), "+r"(reg1), "+r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_r6) *out_r6 = reg6;
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}
