/* RISC OS FileCore SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* FileCore_DiscFormat (SWI &40547): Fills in a disc format structure with parameters for the specified format */
void FileCore_DiscFormat(void *ptr, int r1, int r2, int r3)
{
    register void * reg0 __asm("r0") = ptr;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x40547" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* FileCore_DiscOp (SWI &40540): This call performs various disc operations as specified by bits 0 - 3 of R1: */
void FileCore_DiscOp(void)
{
    __asm__ volatile("swi 0x40540" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* FileCore_FloppyStructure (SWI &40544): Creates a RAM image of a floppy disc map and root directory entry */
void FileCore_FloppyStructure(void *buffer, void *ptr, int r2, void *ptr2)
{
    register void * reg0 __asm("r0") = buffer;
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = r2;
    register void * reg3 __asm("r3") = ptr2;
    __asm__ volatile("swi 0x40544" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* FileCore_LayoutStructure (SWI &40548): Lays out into the specified file a set of structures for its format */
void FileCore_LayoutStructure(int r0, void *ptr, void *ptr2, int handle)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = ptr2;
    register int reg3 __asm("r3") = handle;
    __asm__ volatile("swi 0x40548" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}
