/* RISC OS NetPrint SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* NetPrint_BindPSName (SWI &40206): Converts a printer server’s name to its address, providing it is free */
int NetPrint_BindPSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40206" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* NetPrint_ConvertStatusToString (SWI &40208): *Configure PS sets the configured default network printer server */
void NetPrint_ConvertStatusToString(void)
{
    __asm__ volatile("swi 0x40208" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetPrint_ListServers (SWI &40207): Returns the names of all printer servers */
int NetPrint_ListServers(int format, void *buffer, void *length, int time, int *out_buffer)
{
    register int reg0 __asm("r0") = format;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    register int reg3 __asm("r3") = time;
    __asm__ volatile("swi 0x40207" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_buffer) *out_buffer = reg3;
    return reg0;
}

/* NetPrint_ReadPSName (SWI &40202): Reads the name of your current printer server */
int NetPrint_ReadPSName(void *buffer, void *size)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = size;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40202" : "=r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* NetPrint_ReadPSNumber (SWI &40200): Returns the full station number of your current printer server */
int NetPrint_ReadPSNumber(int *out_net)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40200" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_net) *out_net = reg1;
    return reg0;
}

/* NetPrint_ReadPSTimeouts (SWI &40204): Reads the current values for timeouts used by NetPrint */
int NetPrint_ReadPSTimeouts(int *out_transmit, int *out_machine, int *out_machine2, int *out_receive, int *out_broadcast)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    __asm__ volatile("swi 0x40204" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5) : : "r12", "lr", "memory");
    if (out_broadcast) *out_broadcast = reg5;
    if (out_receive) *out_receive = reg4;
    if (out_machine2) *out_machine2 = reg3;
    if (out_machine) *out_machine = reg2;
    if (out_transmit) *out_transmit = reg1;
    return reg0;
}

/* NetPrint_SetPSName (SWI &40203): Sets by name the printer server used as your current one */
void NetPrint_SetPSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    __asm__ volatile("swi 0x40203" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetPrint_SetPSNumber (SWI &40201): Sets the full station number used as the current printer server */
void NetPrint_SetPSNumber(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    __asm__ volatile("swi 0x40201" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
