/* RISC OS NetFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* NetFS_ConvertDate (SWI &4004B): Converts a file server time and date to a RISC OS time and date */
void NetFS_ConvertDate(void *ptr, void *buffer)
{
    register void * reg0 __asm("r0") = ptr;
    register void * reg1 __asm("r1") = buffer;
    __asm__ volatile("swi 0x4004B" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_DoFSOp (SWI &40048): Commands the current file server to perform an operation */
int NetFS_DoFSOp(int r0, void *buffer, void *buffer2, void *buffer3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register void * reg3 __asm("r3") = buffer3;
    __asm__ volatile("swi 0x40048" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* NetFS_EnableCache (SWI &40051): *AddFS adds a remote file server’s disc to the list of file servers’ discs that are known to */
void NetFS_EnableCache(void)
{
    __asm__ volatile("swi 0x40051" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_EnumerateFS (SWI &4004A): Lists all file servers to which the NetFS software is currently logged on */
int NetFS_EnumerateFS(int r0, void *buffer, void *buffer2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x4004A" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg0;
}

/* NetFS_EnumerateFSContexts (SWI &4004E): Lists all the entries in the list of file servers to which NetFS is currently logged on */
int NetFS_EnumerateFSContexts(int r0, void *buffer, void *buffer2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x4004E" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg0;
}

/* NetFS_EnumerateFSList (SWI &40049): Lists all file servers of which the NetFS software currently knows */
int NetFS_EnumerateFSList(int r0, void *buffer, void *buffer2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x40049" : "+r"(reg0), "+r"(reg3) : "r"(reg1), "r"(reg2) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg0;
}

/* NetFS_ReadCurrentContext (SWI &40044): Unimplemented */
void NetFS_ReadCurrentContext(void)
{
    __asm__ volatile("swi 0x40044" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_ReadFSName (SWI &40042): Reads the name of the your current file server */
int NetFS_ReadFSName(void *buffer, void *buffer2)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40042" : "=r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* NetFS_ReadFSNumber (SWI &40040): Returns the full station number of your current file server */
int NetFS_ReadFSNumber(int *out_r1)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40040" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* NetFS_ReadFSTimeouts (SWI &40046): Reads the current values for timeouts used by NetFS */
int NetFS_ReadFSTimeouts(int *out_r1, int *out_r2, int *out_r3, int *out_r4, int *out_r5)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    __asm__ volatile("swi 0x40046" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5) : : "r12", "lr", "memory");
    if (out_r5) *out_r5 = reg5;
    if (out_r4) *out_r4 = reg4;
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* NetFS_ReadUserId (SWI &4004F): Returns the current user ID if logged on to the current file server */
void NetFS_ReadUserId(void *buffer, void *buffer2)
{
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = buffer2;
    __asm__ volatile("swi 0x4004F" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* NetFS_SetCurrentContext (SWI &40045): Unimplemented */
void NetFS_SetCurrentContext(void)
{
    __asm__ volatile("swi 0x40045" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_SetFSName (SWI &40043): Sets by name the file server used as your current one */
void NetFS_SetFSName(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    __asm__ volatile("swi 0x40043" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_SetFSNumber (SWI &40041): Sets the full station number used as the current file server */
void NetFS_SetFSNumber(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    __asm__ volatile("swi 0x40041" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* NetFS_UpdateFSList (SWI &4004D): Adds names of discs to the list of names held by NetFS */
void NetFS_UpdateFSList(int r0, int r1)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    __asm__ volatile("swi 0x4004D" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
