/* RISC OS PDriver SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* PDriver_AbortJob (SWI &80149). See PRM 3-628. */
void PDriver_AbortJob(int file)
{
    register int reg0 __asm("r0") = file;
    __asm__ volatile("swi 0x80149" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CancelJob (SWI &8014E). See PRM 3-638. */
void PDriver_CancelJob(int file)
{
    register int reg0 __asm("r0") = file;
    __asm__ volatile("swi 0x8014E" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CancelJobWithError (SWI &80152). See PRM 3-642. */
void PDriver_CancelJobWithError(int file, void *block)
{
    register int reg0 __asm("r0") = file;
    register void * reg1 __asm("r1") = block;
    __asm__ volatile("swi 0x80152" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CheckFeatures (SWI &80142). See PRM 3-617. */
void PDriver_CheckFeatures(int mask, int value)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = value;
    __asm__ volatile("swi 0x80142" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_CurrentJob (SWI &80146). See PRM 3-624. */
int PDriver_CurrentJob(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x80146" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_DeclareFont (SWI &80155). See PRM 3-648. */
void PDriver_DeclareFont(int handle, void *name, int flags)
{
    register int reg0 __asm("r0") = handle;
    register void * reg1 __asm("r1") = name;
    register int reg2 __asm("r2") = flags;
    __asm__ volatile("swi 0x80155" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* PDriver_DrawPage (SWI &8014C). See PRM 3-635. */
int PDriver_DrawPage(int count, void *block, int page, void *string, int *out_identification)
{
    register int reg0 __asm("r0") = count;
    register void * reg1 __asm("r1") = block;
    register int reg2 __asm("r2") = page;
    register void * reg3 __asm("r3") = string;
    __asm__ volatile("swi 0x8014C" : "+r"(reg0), "+r"(reg2) : "r"(reg1), "r"(reg3) : "r12", "lr", "memory");
    if (out_identification) *out_identification = reg2;
    return reg0;
}

/* PDriver_EndJob (SWI &80148). See PRM 3-626. */
void PDriver_EndJob(int file)
{
    register int reg0 __asm("r0") = file;
    __asm__ volatile("swi 0x80148" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_EnumerateDrivers (SWI &80159). See PRM 3-655. */
int PDriver_EnumerateDrivers(int handle, int *out_printer)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x80159" : "+r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_printer) *out_printer = reg1;
    return reg0;
}

/* PDriver_EnumerateJobs (SWI &80150). See PRM 3-640. */
int PDriver_EnumerateJobs(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x80150" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_FontSWI (SWI &80147). See PRM 3-625. */
void PDriver_FontSWI(void)
{
    __asm__ volatile("swi 0x80147" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_GetRectangle (SWI &8014D). See PRM 3-637. */
int PDriver_GetRectangle(void *block, int *out_identification)
{
    register void * reg1 __asm("r1") = block;
    register int reg0 __asm("r0");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x8014D" : "=r"(reg0), "=r"(reg2) : "r"(reg1) : "r3", "r12", "lr", "memory");
    if (out_identification) *out_identification = reg2;
    return reg0;
}

/* PDriver_Info (SWI &80140). See PRM 3-611. */
int PDriver_Info(int *out_value, int *out_value2, int *out_features, int *out_ptr, int *out_value3, int *out_value4, int *out_printer)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    register int reg7 __asm("r7");
    __asm__ volatile("swi 0x80140" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7) : : "r12", "lr", "memory");
    if (out_printer) *out_printer = reg7;
    if (out_value4) *out_value4 = reg6;
    if (out_value3) *out_value3 = reg5;
    if (out_ptr) *out_ptr = reg4;
    if (out_features) *out_features = reg3;
    if (out_value2) *out_value2 = reg2;
    if (out_value) *out_value = reg1;
    return reg0;
}

/* PDriver_PageSize (SWI &80143). See PRM 3-618. */
int PDriver_PageSize(int *out_size, int *out_left, int *out_bottom, int *out_right, int *out_top)
{
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x80143" : "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r0", "r12", "lr", "memory");
    if (out_top) *out_top = reg6;
    if (out_right) *out_right = reg5;
    if (out_bottom) *out_bottom = reg4;
    if (out_left) *out_left = reg3;
    if (out_size) *out_size = reg2;
    return reg1;
}

/* PDriver_RemoveDriver (SWI &80157). See PRM 3-652. */
void PDriver_RemoveDriver(int printer)
{
    register int reg0 __asm("r0") = printer;
    __asm__ volatile("swi 0x80157" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_Reset (SWI &8014A). See PRM 3-630. */
void PDriver_Reset(void)
{
    __asm__ volatile("swi 0x8014A" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_ScreenDump (SWI &8014F). See PRM 3-639. */
void PDriver_ScreenDump(int file)
{
    register int reg0 __asm("r0") = file;
    __asm__ volatile("swi 0x8014F" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* PDriver_SelectDriver (SWI &80158). See PRM 3-653. */
int PDriver_SelectDriver(int printer)
{
    register int reg0 __asm("r0") = printer;
    __asm__ volatile("swi 0x80158" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SelectIllustration (SWI &80153). See PRM 3-644. */
int PDriver_SelectIllustration(int file, void *string)
{
    register int reg0 __asm("r0") = file;
    register void * reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x80153" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SelectJob (SWI &80145). See PRM 3-622. */
int PDriver_SelectJob(int file, void *string)
{
    register int reg0 __asm("r0") = file;
    register void * reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x80145" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* PDriver_SetPrinter (SWI &80151). See PRM 3-641. */
void PDriver_SetPrinter(void)
{
    __asm__ volatile("swi 0x80151" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
