/* RISC OS MessageTrans SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* MessageTrans_CloseFile (SWI &41504): Closes a message file */
void MessageTrans_CloseFile(void *message)
{
    register void * reg0 __asm("r0") = message;
    __asm__ volatile("swi 0x41504" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* MessageTrans_CopyError (SWI &41508): Copies an error to one of the MessageTrans internal buffers */
void MessageTrans_CopyError(void *block)
{
    register void * reg0 __asm("r0") = block;
    __asm__ volatile("swi 0x41508" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* MessageTrans_FileInfo (SWI &41500): Gives information about a message file */
int MessageTrans_FileInfo(void *filename, int *out_size)
{
    register void * reg1 __asm("r1") = filename;
    register int reg0 __asm("r0");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x41500" : "=r"(reg0), "=r"(reg2) : "r"(reg1) : "r3", "r12", "lr", "memory");
    if (out_size) *out_size = reg2;
    return reg0;
}

/* MessageTrans_MakeMenus (SWI &41503): Sets up a menu structure from a definition containing references to tokens */
void MessageTrans_MakeMenus(void *message, void *ptr, void *buffer, void *size)
{
    register void * reg0 __asm("r0") = message;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = buffer;
    register void * reg3 __asm("r3") = size;
    __asm__ volatile("swi 0x41503" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* MessageTrans_OpenFile (SWI &41501): Opens a message file */
void MessageTrans_OpenFile(void *ptr, void *filename, void *buffer)
{
    register void * reg0 __asm("r0") = ptr;
    register void * reg1 __asm("r1") = filename;
    register void * reg2 __asm("r2") = buffer;
    __asm__ volatile("swi 0x41501" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}
