/* RISC OS Hourglass SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Hourglass_Colours (SWI &406C6): Sets the colours used to display the hourglass */
int Hourglass_Colours(int colour, int colour2, int *out_colour)
{
    register int reg0 __asm("r0") = colour;
    register int reg1 __asm("r1") = colour2;
    __asm__ volatile("swi 0x406C6" : "+r"(reg0), "+r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_colour) *out_colour = reg1;
    return reg0;
}

/* Hourglass_LEDs (SWI &406C5): Controls the display indicators above and below the hourglass */
int Hourglass_LEDs(int value)
{
    register int reg0 __asm("r0") = value;
    __asm__ volatile("swi 0x406C5" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Hourglass_Off (SWI &406C1): Turns off the hourglass */
void Hourglass_Off(void)
{
    __asm__ volatile("swi 0x406C1" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Hourglass_On (SWI &406C0): Turns on the hourglass */
void Hourglass_On(void)
{
    __asm__ volatile("swi 0x406C0" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Hourglass_Percentage (SWI &406C4): Displays a percentage below the hourglass */
void Hourglass_Percentage(int percentage)
{
    register int reg0 __asm("r0") = percentage;
    __asm__ volatile("swi 0x406C4" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Hourglass_Smash (SWI &406C2): Turns off the hourglass immediately */
void Hourglass_Smash(void)
{
    __asm__ volatile("swi 0x406C2" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Hourglass_Start (SWI &406C3): Turns on the hourglass after a given delay */
void Hourglass_Start(int delay)
{
    register int reg0 __asm("r0") = delay;
    __asm__ volatile("swi 0x406C3" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}
