/* RISC OS MakePSFont SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* MakePSFont_MakeFont (SWI &43440). See PRM 3-742. */
void MakePSFont_MakeFont(void)
{
    __asm__ volatile("swi 0x43440" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}
