/* RISC OS ColourTrans SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ColourTrans_ColourNumberToGCOL (SWI &4074D). See PRM 3-367. */
int ColourTrans_ColourNumberToGCOL(int colour)
{
    register int reg0 __asm("r0") = colour;
    __asm__ volatile("swi 0x4074D" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ConvertCIEToRGB (SWI &40756). See PRM 3-381. */
int ColourTrans_ConvertCIEToRGB(int value, int value2, int value3, int *out_green, int *out_blue)
{
    register int reg0 __asm("r0") = value;
    register int reg1 __asm("r1") = value2;
    register int reg2 __asm("r2") = value3;
    __asm__ volatile("swi 0x40756" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_blue) *out_blue = reg2;
    if (out_green) *out_green = reg1;
    return reg0;
}

/* ColourTrans_ConvertCMYKToRGB (SWI &4075B). See PRM 3-391. */
int ColourTrans_ConvertCMYKToRGB(int cyan, int magenta, int yellow, int key, int *out_green, int *out_blue)
{
    register int reg0 __asm("r0") = cyan;
    register int reg1 __asm("r1") = magenta;
    register int reg2 __asm("r2") = yellow;
    register int reg3 __asm("r3") = key;
    __asm__ volatile("swi 0x4075B" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : "r"(reg3) : "r12", "lr", "memory");
    if (out_blue) *out_blue = reg2;
    if (out_green) *out_green = reg1;
    return reg0;
}

/* ColourTrans_ConvertDeviceColour (SWI &40753). See PRM 3-376. */
int ColourTrans_ConvertDeviceColour(int colour, void *ptr)
{
    register int reg1 __asm("r1") = colour;
    register void * reg3 __asm("r3") = ptr;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40753" : "=r"(reg2) : "r"(reg1), "r"(reg3) : "r0", "r12", "lr", "memory");
    return reg2;
}

/* ColourTrans_ConvertDevicePalette (SWI &40754). See PRM 3-377. */
void ColourTrans_ConvertDevicePalette(int count, void *colour, void *colour2, void *ptr)
{
    register int reg0 __asm("r0") = count;
    register void * reg1 __asm("r1") = colour;
    register void * reg2 __asm("r2") = colour2;
    register void * reg3 __asm("r3") = ptr;
    __asm__ volatile("swi 0x40754" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* ColourTrans_ConvertHSVToRGB (SWI &40759). See PRM 3-387. */
int ColourTrans_ConvertHSVToRGB(int hue, int saturation, int value, int *out_green, int *out_blue)
{
    register int reg0 __asm("r0") = hue;
    register int reg1 __asm("r1") = saturation;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x40759" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_blue) *out_blue = reg2;
    if (out_green) *out_green = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToCIE (SWI &40755). See PRM 3-379. */
int ColourTrans_ConvertRGBToCIE(int red, int green, int blue, int *out_value, int *out_value2)
{
    register int reg0 __asm("r0") = red;
    register int reg1 __asm("r1") = green;
    register int reg2 __asm("r2") = blue;
    __asm__ volatile("swi 0x40755" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_value2) *out_value2 = reg2;
    if (out_value) *out_value = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToCMYK (SWI &4075A). See PRM 3-389. */
int ColourTrans_ConvertRGBToCMYK(int red, int green, int blue, int *out_magenta, int *out_yellow, int *out_key)
{
    register int reg0 __asm("r0") = red;
    register int reg1 __asm("r1") = green;
    register int reg2 __asm("r2") = blue;
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4075A" : "+r"(reg0), "+r"(reg1), "+r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_key) *out_key = reg3;
    if (out_yellow) *out_yellow = reg2;
    if (out_magenta) *out_magenta = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToHSV (SWI &40758). See PRM 3-385. */
int ColourTrans_ConvertRGBToHSV(int red, int green, int blue, int *out_saturation, int *out_value)
{
    register int reg0 __asm("r0") = red;
    register int reg1 __asm("r1") = green;
    register int reg2 __asm("r2") = blue;
    __asm__ volatile("swi 0x40758" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_value) *out_value = reg2;
    if (out_saturation) *out_saturation = reg1;
    return reg0;
}

/* ColourTrans_GCOLToColourNumber (SWI &4074C). See PRM 3-366. */
int ColourTrans_GCOLToColourNumber(int gcol)
{
    register int reg0 __asm("r0") = gcol;
    __asm__ volatile("swi 0x4074C" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_GenerateTable (SWI &40763). See PRM 3-406. */
void ColourTrans_GenerateTable(void)
{
    __asm__ volatile("swi 0x40763" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_InvalidateCache (SWI &40750). See PRM 3-372. */
void ColourTrans_InvalidateCache(void)
{
    __asm__ volatile("swi 0x40750" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_MiscOp (SWI &4075F). See PRM 3-399. */
void ColourTrans_MiscOp(void)
{
    __asm__ volatile("swi 0x4075F" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_ReadCalibration (SWI &40752). See PRM 3-375. */
int ColourTrans_ReadCalibration(void *size)
{
    register void * reg0 __asm("r0") = size;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40752" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* ColourTrans_ReturnColourNumber (SWI &40744). See PRM 3-352. */
int ColourTrans_ReturnColourNumber(int palette_entry)
{
    register int reg0 __asm("r0") = palette_entry;
    __asm__ volatile("swi 0x40744" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnColourNumberForMode (SWI &40746). See PRM 3-355. */
int ColourTrans_ReturnColourNumberForMode(int palette_entry, int mode, void *palette)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg1 __asm("r1") = mode;
    register void * reg2 __asm("r2") = palette;
    __asm__ volatile("swi 0x40746" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnFontColours (SWI &4074E). See PRM 3-368. */
int ColourTrans_ReturnFontColours(int font, int palette_entry, int palette_entry2, int offset, int *out_offset)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1") = palette_entry;
    register int reg2 __asm("r2") = palette_entry2;
    register int reg3 __asm("r3") = offset;
    __asm__ volatile("swi 0x4074E" : "+r"(reg2), "+r"(reg3) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    return reg2;
}

/* ColourTrans_ReturnGCOL (SWI &40742). See PRM 3-348. */
int ColourTrans_ReturnGCOL(int palette_entry)
{
    register int reg0 __asm("r0") = palette_entry;
    __asm__ volatile("swi 0x40742" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnGCOLForMode (SWI &40745). See PRM 3-353. */
int ColourTrans_ReturnGCOLForMode(int palette_entry, int mode, void *palette)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg1 __asm("r1") = mode;
    register void * reg2 __asm("r2") = palette;
    __asm__ volatile("swi 0x40745" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppColourNumber (SWI &40749). See PRM 3-361. */
int ColourTrans_ReturnOppColourNumber(int palette_entry)
{
    register int reg0 __asm("r0") = palette_entry;
    __asm__ volatile("swi 0x40749" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppColourNumberForMode (SWI &4074B). See PRM 3-364. */
int ColourTrans_ReturnOppColourNumberForMode(int palette_entry, int mode, void *palette)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg1 __asm("r1") = mode;
    register void * reg2 __asm("r2") = palette;
    __asm__ volatile("swi 0x4074B" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppGCOL (SWI &40747). See PRM 3-357. */
int ColourTrans_ReturnOppGCOL(int palette_entry)
{
    register int reg0 __asm("r0") = palette_entry;
    __asm__ volatile("swi 0x40747" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppGCOLForMode (SWI &4074A). See PRM 3-362. */
int ColourTrans_ReturnOppGCOLForMode(int palette_entry, int mode, void *palette)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg1 __asm("r1") = mode;
    register void * reg2 __asm("r2") = palette;
    __asm__ volatile("swi 0x4074A" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_SetCalibration (SWI &40751). See PRM 3-374. */
void ColourTrans_SetCalibration(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x40751" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_SetFontColours (SWI &4074F). See PRM 3-370. */
int ColourTrans_SetFontColours(int font, int palette_entry, int palette_entry2, int offset, int *out_offset)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1") = palette_entry;
    register int reg2 __asm("r2") = palette_entry2;
    register int reg3 __asm("r3") = offset;
    __asm__ volatile("swi 0x4074F" : "+r"(reg2), "+r"(reg3) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    return reg2;
}

/* ColourTrans_SetOppTextColour (SWI &40762). See PRM 3-403. */
int ColourTrans_SetOppTextColour(int palette_entry, int colour)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg3 __asm("r3") = colour;
    __asm__ volatile("swi 0x40762" : "+r"(reg0) : "r"(reg3) : "r1", "r2", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_SetTextColour (SWI &40761). See PRM 3-401. */
int ColourTrans_SetTextColour(int palette_entry, int colour)
{
    register int reg0 __asm("r0") = palette_entry;
    register int reg3 __asm("r3") = colour;
    __asm__ volatile("swi 0x40761" : "+r"(reg0) : "r"(reg3) : "r1", "r2", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_WriteCalibrationToFile (SWI &40757). See PRM 3-383. */
void ColourTrans_WriteCalibrationToFile(int flags, int file)
{
    register int reg0 __asm("r0") = flags;
    register int reg1 __asm("r1") = file;
    __asm__ volatile("swi 0x40757" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_WriteLoadingsToFile (SWI &40760). See PRM 3-400. */
void ColourTrans_WriteLoadingsToFile(int file)
{
    register int reg1 __asm("r1") = file;
    __asm__ volatile("swi 0x40760" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}
