/* RISC OS Font SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Font_ApplyFields (SWI &400A7). See PRM 3-504. */
void Font_ApplyFields(void *ptr, void *ptr2, void *size, void *size2)
{
    register void * reg0 __asm("r0") = ptr;
    register void * reg1 __asm("r1") = ptr2;
    register void * reg2 __asm("r2") = size;
    register void * reg3 __asm("r3") = size2;
    __asm__ volatile("swi 0x400A7" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* Font_CacheAddr (SWI &40080). See PRM 3-426. */
int Font_CacheAddr(int *out_size, int *out_amount)
{
    register int reg0 __asm("r0");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x40080" : "=r"(reg0), "=r"(reg2), "=r"(reg3) : : "r1", "r12", "lr", "memory");
    if (out_amount) *out_amount = reg3;
    if (out_size) *out_size = reg2;
    return reg0;
}

/* Font_CharBBox (SWI &4008E). See PRM 3-454. */
int Font_CharBBox(int font, int ascii, int flags, int *out_bbox, int *out_bbox2, int *out_bbox3)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1") = ascii;
    register int reg2 __asm("r2") = flags;
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    __asm__ volatile("swi 0x4008E" : "+r"(reg1), "+r"(reg2), "=r"(reg3), "=r"(reg4) : "r"(reg0) : "r12", "lr", "memory");
    if (out_bbox3) *out_bbox3 = reg4;
    if (out_bbox2) *out_bbox2 = reg3;
    if (out_bbox) *out_bbox = reg2;
    return reg1;
}

/* Font_ConverttoOS (SWI &40088). See PRM 3-446. */
int Font_ConverttoOS(int x, int y, int *out_y)
{
    register int reg1 __asm("r1") = x;
    register int reg2 __asm("r2") = y;
    __asm__ volatile("swi 0x40088" : "+r"(reg1), "+r"(reg2) : : "r0", "r3", "r12", "lr", "memory");
    if (out_y) *out_y = reg2;
    return reg1;
}

/* Font_Converttopoints (SWI &40089). See PRM 3-447. */
int Font_Converttopoints(int x, int y, int *out_y)
{
    register int reg1 __asm("r1") = x;
    register int reg2 __asm("r2") = y;
    __asm__ volatile("swi 0x40089" : "+r"(reg1), "+r"(reg2) : : "r0", "r3", "r12", "lr", "memory");
    if (out_y) *out_y = reg2;
    return reg1;
}

/* Font_CurrentFont (SWI &4008B). See PRM 3-449. */
int Font_CurrentFont(int *out_colour, int *out_colour2, int *out_offset)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4008B" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    if (out_colour2) *out_colour2 = reg2;
    if (out_colour) *out_colour = reg1;
    return reg0;
}

/* Font_CurrentRGB (SWI &400A3). See PRM 3-497. */
int Font_CurrentRGB(int *out_colour, int *out_colour2, int *out_offset)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x400A3" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    if (out_colour2) *out_colour2 = reg2;
    if (out_colour) *out_colour = reg1;
    return reg0;
}

/* Font_FindCaret (SWI &4008D). See PRM 3-452. */
int Font_FindCaret(void *string, int offset, int offset2, int *out_offset, int *out_count, int *out_string)
{
    register void * reg1 __asm("r1") = string;
    register int reg2 __asm("r2") = offset;
    register int reg3 __asm("r3") = offset2;
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    __asm__ volatile("swi 0x4008D" : "+r"(reg2), "+r"(reg3), "=r"(reg4), "=r"(reg5) : "r"(reg1) : "r0", "r12", "lr", "memory");
    if (out_string) *out_string = reg5;
    if (out_count) *out_count = reg4;
    if (out_offset) *out_offset = reg3;
    return reg2;
}

/* Font_FindField (SWI &400A6). See PRM 3-503. */
void Font_FindField(void *ptr, int character)
{
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = character;
    __asm__ volatile("swi 0x400A6" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* Font_FutureFont (SWI &4008C). See PRM 3-451. */
int Font_FutureFont(int *out_colour, int *out_colour2, int *out_offset)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4008C" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    if (out_colour2) *out_colour2 = reg2;
    if (out_colour) *out_colour = reg1;
    return reg0;
}

/* Font_FutureRGB (SWI &400A4). See PRM 3-499. */
int Font_FutureRGB(int *out_colour, int *out_colour2, int *out_offset)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x400A4" : "=r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_offset) *out_offset = reg3;
    if (out_colour2) *out_colour2 = reg2;
    if (out_colour) *out_colour = reg1;
    return reg0;
}

/* Font_LookupFont (SWI &400A8). See PRM 3-506. */
int Font_LookupFont(int font, int arg1, int arg2)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1") = arg1;
    register int reg2 __asm("r2") = arg2;
    __asm__ volatile("swi 0x400A8" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Font_LoseFont (SWI &40082). See PRM 3-431. */
void Font_LoseFont(int font)
{
    register int reg0 __asm("r0") = font;
    __asm__ volatile("swi 0x40082" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Font_Paint (SWI &40086). See PRM 3-438. */
void Font_Paint(void)
{
    __asm__ volatile("swi 0x40086" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Font_ReadColourTable (SWI &40098). See PRM 3-473. */
void Font_ReadColourTable(void *ptr)
{
    register void * reg1 __asm("r1") = ptr;
    __asm__ volatile("swi 0x40098" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Font_ReadDefn (SWI &40083). See PRM 3-432. */
int Font_ReadDefn(int font, void *size, int arg3, int *out_size, int *out_value, int *out_value2, int *out_age, int *out_usage)
{
    register int reg0 __asm("r0") = font;
    register void * reg1 __asm("r1") = size;
    register int reg3 __asm("r3") = arg3;
    register int reg2 __asm("r2");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    register int reg7 __asm("r7");
    __asm__ volatile("swi 0x40083" : "+r"(reg3), "=r"(reg2), "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_usage) *out_usage = reg7;
    if (out_age) *out_age = reg6;
    if (out_value2) *out_value2 = reg5;
    if (out_value) *out_value = reg4;
    if (out_size) *out_size = reg3;
    return reg2;
}

/* Font_ReadEncodingFilename (SWI &400A5). See PRM 3-501. */
int Font_ReadEncodingFilename(int font, void *buffer, void *length)
{
    register int reg0 __asm("r0") = font;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x400A5" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* Font_ReadFontMax (SWI &4009C). See PRM 3-480. */
int Font_ReadFontMax(int *out_value)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x4009C" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_value) *out_value = reg1;
    return reg0;
}

/* Font_ReadFontPrefix (SWI &4009D). See PRM 3-481. */
void Font_ReadFontPrefix(int font, void *buffer, void *length)
{
    register int reg0 __asm("r0") = font;
    register void * reg1 __asm("r1") = buffer;
    register void * reg2 __asm("r2") = length;
    __asm__ volatile("swi 0x4009D" : : "r"(reg0), "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
}

/* Font_ReadInfo (SWI &40084). See PRM 3-434. */
int Font_ReadInfo(int font, int *out_y, int *out_x, int *out_y2)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    __asm__ volatile("swi 0x40084" : "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4) : "r"(reg0) : "r12", "lr", "memory");
    if (out_y2) *out_y2 = reg4;
    if (out_x) *out_x = reg3;
    if (out_y) *out_y = reg2;
    return reg1;
}

/* Font_ReadScaleFactor (SWI &4008F). See PRM 3-456. */
int Font_ReadScaleFactor(int *out_value)
{
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4008F" : "=r"(reg1), "=r"(reg2) : : "r0", "r3", "r12", "lr", "memory");
    if (out_value) *out_value = reg2;
    return reg1;
}

/* Font_ReadThresholds (SWI &40094). See PRM 3-465. */
void Font_ReadThresholds(void *buffer)
{
    register void * reg1 __asm("r1") = buffer;
    __asm__ volatile("swi 0x40094" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Font_SetColourTable (SWI &400A2). See PRM 3-495. */
void Font_SetColourTable(void)
{
    __asm__ volatile("swi 0x400A2" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Font_SetFont (SWI &4008A). See PRM 3-448. */
void Font_SetFont(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x4008A" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Font_SetFontColours (SWI &40092). See PRM 3-461. */
void Font_SetFontColours(int font, int colour, int colour2, int offset)
{
    register int reg0 __asm("r0") = font;
    register int reg1 __asm("r1") = colour;
    register int reg2 __asm("r2") = colour2;
    register int reg3 __asm("r3") = offset;
    __asm__ volatile("swi 0x40092" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* Font_SetScaleFactor (SWI &40090). See PRM 3-457. */
void Font_SetScaleFactor(int arg1, int arg2)
{
    register int reg1 __asm("r1") = arg1;
    register int reg2 __asm("r2") = arg2;
    __asm__ volatile("swi 0x40090" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}

/* Font_SetThresholds (SWI &40095). See PRM 3-468. */
void Font_SetThresholds(void *ptr)
{
    register void * reg1 __asm("r1") = ptr;
    __asm__ volatile("swi 0x40095" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}

/* Font_StringBBox (SWI &40097). See PRM 3-471. */
int Font_StringBBox(void *string, int *out_bbox, int *out_bbox2)
{
    register void * reg1 __asm("r1") = string;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    __asm__ volatile("swi 0x40097" : "=r"(reg2), "=r"(reg3), "=r"(reg4) : "r"(reg1) : "r0", "r12", "lr", "memory");
    if (out_bbox2) *out_bbox2 = reg4;
    if (out_bbox) *out_bbox = reg3;
    return reg2;
}

/* Font_SwitchOutputToBuffer (SWI &4009E). See PRM 3-483. */
int Font_SwitchOutputToBuffer(int flags, void *buffer)
{
    register int reg0 __asm("r0") = flags;
    register void * reg1 __asm("r1") = buffer;
    __asm__ volatile("swi 0x4009E" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Font_UnCacheFile (SWI &4009A). See PRM 3-476. */
void Font_UnCacheFile(void *filename, int flags)
{
    register void * reg1 __asm("r1") = filename;
    register int reg2 __asm("r2") = flags;
    __asm__ volatile("swi 0x4009A" : : "r"(reg1), "r"(reg2) : "r0", "r3", "r12", "lr", "memory");
}
