/* RISC OS Econet SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Econet_AbandonAndReadReceive (SWI &40018). See PRM 2-695. */
int Econet_AbandonAndReadReceive(int handle, int *out_flags, int *out_port, int *out_station, int *out_net, int *out_buffer, int *out_size)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40018" : "+r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_size) *out_size = reg6;
    if (out_buffer) *out_buffer = reg5;
    if (out_net) *out_net = reg4;
    if (out_station) *out_station = reg3;
    if (out_port) *out_port = reg2;
    if (out_flags) *out_flags = reg1;
    return reg0;
}

/* Econet_AbandonReceive (SWI &40003). See PRM 2-663. */
int Econet_AbandonReceive(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40003" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_AbandonTransmit (SWI &40008). See PRM 2-671. */
int Econet_AbandonTransmit(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40008" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_AllocatePort (SWI &40013). See PRM 2-688. */
int Econet_AllocatePort(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40013" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_ClaimPort (SWI &40015). See PRM 2-690. */
void Econet_ClaimPort(int port)
{
    register int reg0 __asm("r0") = port;
    __asm__ volatile("swi 0x40015" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_DeAllocatePort (SWI &40014). See PRM 2-689. */
void Econet_DeAllocatePort(int port)
{
    register int reg0 __asm("r0") = port;
    __asm__ volatile("swi 0x40014" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_EnumerateReceive (SWI &40005). See PRM 2-666. */
void Econet_EnumerateReceive(void *block)
{
    register void * reg0 __asm("r0") = block;
    __asm__ volatile("swi 0x40005" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_EnumerateTransmit (SWI &4001F). See PRM 5a-274. */
void Econet_EnumerateTransmit(void *block)
{
    register void * reg0 __asm("r0") = block;
    __asm__ volatile("swi 0x4001F" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_ExamineReceive (SWI &40001). See PRM 2-659. */
int Econet_ExamineReceive(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40001" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_HardwareAddresses (SWI &40020). See PRM 5a-276. */
int Econet_HardwareAddresses(int *out_address, int *out_mask)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40020" : "=r"(reg0), "=r"(reg1), "=r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_mask) *out_mask = reg2;
    if (out_address) *out_address = reg1;
    return reg0;
}

/* Econet_InetRxDirect (SWI &4001D). See PRM 5a-271. */
void Econet_InetRxDirect(void)
{
    __asm__ volatile("swi 0x4001D" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_NetworkParameters (SWI &40021). See PRM 5a-278. */
void Econet_NetworkParameters(void)
{
    __asm__ volatile("swi 0x40021" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_NetworkState (SWI &4001A). See PRM 2-698. */
int Econet_NetworkState(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001A" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_PacketSize (SWI &4001B). See PRM 2-700. */
int Econet_PacketSize(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001B" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_PollTransmit (SWI &40007). See PRM 2-669. */
int Econet_PollTransmit(int handle)
{
    register int reg0 __asm("r0") = handle;
    __asm__ volatile("swi 0x40007" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_PrintBanner (SWI &40010). See PRM 2-684. */
void Econet_PrintBanner(void)
{
    __asm__ volatile("swi 0x40010" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_ReadLocalStationAndNet (SWI &4000A). See PRM 2-674. */
int Econet_ReadLocalStationAndNet(int *out_net)
{
    register int reg0 __asm("r0");
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x4000A" : "=r"(reg0), "=r"(reg1) : : "r2", "r3", "r12", "lr", "memory");
    if (out_net) *out_net = reg1;
    return reg0;
}

/* Econet_ReadProtection (SWI &4000D). See PRM 2-679. */
int Econet_ReadProtection(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x4000D" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_ReadReceive (SWI &40002). See PRM 2-661. */
int Econet_ReadReceive(int handle, int *out_flags, int *out_port, int *out_station, int *out_net, int *out_buffer, int *out_size)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1");
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40002" : "+r"(reg0), "=r"(reg1), "=r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_size) *out_size = reg6;
    if (out_buffer) *out_buffer = reg5;
    if (out_net) *out_net = reg4;
    if (out_station) *out_station = reg3;
    if (out_port) *out_port = reg2;
    if (out_flags) *out_flags = reg1;
    return reg0;
}

/* Econet_ReadStationNumber (SWI &4000F). See PRM 2-683. */
int Econet_ReadStationNumber(void *string, int *out_net)
{
    register void * reg1 __asm("r1") = string;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4000F" : "=r"(reg2), "=r"(reg3) : "r"(reg1) : "r0", "r12", "lr", "memory");
    if (out_net) *out_net = reg3;
    return reg2;
}

/* Econet_ReadTransportName (SWI &4001C). See PRM 2-702. */
int Econet_ReadTransportName(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4001C" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_ReadTransportType (SWI &40011). See PRM 2-685. */
int Econet_ReadTransportType(int station, int net, int arg2)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    register int reg2 __asm("r2") = arg2;
    __asm__ volatile("swi 0x40011" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_ReleasePort (SWI &40012). See PRM 2-687. */
void Econet_ReleasePort(int port)
{
    register int reg0 __asm("r0") = port;
    __asm__ volatile("swi 0x40012" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Econet_SetProtection (SWI &4000E). See PRM 2-681. */
int Econet_SetProtection(int mask, int mask2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = mask2;
    __asm__ volatile("swi 0x4000E" : "+r"(reg0) : "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Econet_Version (SWI &40019). See PRM 2-697. */
int Econet_Version(int station, int net)
{
    register int reg0 __asm("r0") = station;
    register int reg1 __asm("r1") = net;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40019" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Econet_WaitForReception (SWI &40004). See PRM 2-664. */
int Econet_WaitForReception(int handle, int delay, int arg2, int *out_flags, int *out_port, int *out_station, int *out_net, int *out_buffer, int *out_size)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = delay;
    register int reg2 __asm("r2") = arg2;
    register int reg3 __asm("r3");
    register int reg4 __asm("r4");
    register int reg5 __asm("r5");
    register int reg6 __asm("r6");
    __asm__ volatile("swi 0x40004" : "+r"(reg0), "+r"(reg1), "+r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6) : : "r12", "lr", "memory");
    if (out_size) *out_size = reg6;
    if (out_buffer) *out_buffer = reg5;
    if (out_net) *out_net = reg4;
    if (out_station) *out_station = reg3;
    if (out_port) *out_port = reg2;
    if (out_flags) *out_flags = reg1;
    return reg0;
}
