/* RISC OS FPEmulator SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* FPEmulator_Version (SWI &40480): Returns the version number of the floating point emulator */
int FPEmulator_Version(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40480" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}
