/* RISC OS ADFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ADFS_ControllerType (SWI &40248). See PRM 2-294. */
void ADFS_ControllerType(int drive)
{
    register int reg0 __asm("r0") = drive;
    __asm__ volatile("swi 0x40248" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_DescribeDisc (SWI &40245). See PRM 2-290. */
void ADFS_DescribeDisc(void)
{
    __asm__ volatile("swi 0x40245" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_DiscOp (SWI &40240). See PRM 2-283. */
void ADFS_DiscOp(void)
{
    __asm__ volatile("swi 0x40240" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_Drives (SWI &40242). See PRM 2-286. */
void ADFS_Drives(void)
{
    __asm__ volatile("swi 0x40242" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_ECCSAndRetries (SWI &40250). See PRM 2-303. */
void ADFS_ECCSAndRetries(void)
{
    __asm__ volatile("swi 0x40250" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FlpProcessDCB (SWI &40247). See PRM 2-293. */
void ADFS_FlpProcessDCB(void)
{
    __asm__ volatile("swi 0x40247" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FreeSpace (SWI &40243). See PRM 2-287. */
void ADFS_FreeSpace(void)
{
    __asm__ volatile("swi 0x40243" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_FreeSpace64 (SWI &40252). See PRM 5a-189. */
void ADFS_FreeSpace64(void)
{
    __asm__ volatile("swi 0x40252" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_LockIDE (SWI &40251). See PRM 5a-188. */
void ADFS_LockIDE(int flags)
{
    register int reg0 __asm("r0") = flags;
    __asm__ volatile("swi 0x40251" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_MiscOp (SWI &4024C). See PRM 2-302. */
void ADFS_MiscOp(void)
{
    __asm__ volatile("swi 0x4024C" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_Retries (SWI &40244). See PRM 2-288. */
int ADFS_Retries(int mask, int value, int *out_value, int *out_value2)
{
    register int reg0 __asm("r0") = mask;
    register int reg1 __asm("r1") = value;
    register int reg2 __asm("r2");
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x40244" : "+r"(reg1), "=r"(reg2), "=r"(reg3) : "r"(reg0) : "r12", "lr", "memory");
    if (out_value2) *out_value2 = reg3;
    if (out_value) *out_value = reg2;
    return reg1;
}

/* ADFS_SectorDiscOp (SWI &4024D). See PRM 5a-187. */
void ADFS_SectorDiscOp(void)
{
    __asm__ volatile("swi 0x4024D" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ADFS_VetFormat (SWI &40246). See PRM 2-291. */
void ADFS_VetFormat(void *ptr, int parameter)
{
    register void * reg0 __asm("r0") = ptr;
    register int reg1 __asm("r1") = parameter;
    __asm__ volatile("swi 0x40246" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}
