/* RISC OS ResourceFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ResourceFS_DeregisterFiles (SWI &41B41): *ResourceFS selects the Resource Filing System as the filing system for subsequent */
void ResourceFS_DeregisterFiles(void)
{
    __asm__ volatile("swi 0x41B41" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ResourceFS_RegisterFiles (SWI &41B40): Add file(s) to the ResourceFS structure */
void ResourceFS_RegisterFiles(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x41B40" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}
