/* RISC OS ColourTrans SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* ColourTrans_ColourNumberToGCOL (SWI &4074D): Translates a colour number to a GCOL */
int ColourTrans_ColourNumberToGCOL(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x4074D" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ConvertCIEToRGB (SWI &40756): Converts industry standard CIE colours to RISC OS RGB colours */
int ColourTrans_ConvertCIEToRGB(int value, int value2, int value3, int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0") = value;
    register int reg1 __asm("r1") = value2;
    register int reg2 __asm("r2") = value3;
    __asm__ volatile("swi 0x40756" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_ConvertCMYKToRGB (SWI &4075B): Converts from the CMYK model to RISC OS RGB colours */
int ColourTrans_ConvertCMYKToRGB(int r0, int r1, int r2, int r3, int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x4075B" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : "r"(reg3) : "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_ConvertDeviceColour (SWI &40753): Converts a device colour to a standard colour */
int ColourTrans_ConvertDeviceColour(int r1, void *ptr)
{
    register int reg1 __asm("r1") = r1;
    register void * reg3 __asm("r3") = ptr;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x40753" : "=r"(reg2) : "r"(reg1), "r"(reg3) : "r0", "r12", "lr", "memory");
    return reg2;
}

/* ColourTrans_ConvertDevicePalette (SWI &40754): Converts a device palette to standard colours */
void ColourTrans_ConvertDevicePalette(int r0, void *ptr, void *ptr2, void *ptr3)
{
    register int reg0 __asm("r0") = r0;
    register void * reg1 __asm("r1") = ptr;
    register void * reg2 __asm("r2") = ptr2;
    register void * reg3 __asm("r3") = ptr3;
    __asm__ volatile("swi 0x40754" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* ColourTrans_ConvertHSVToRGB (SWI &40759): Converts hue, saturation and value into corresponding RISC OS RGB colours */
int ColourTrans_ConvertHSVToRGB(int r0, int r1, int value, int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = value;
    __asm__ volatile("swi 0x40759" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToCIE (SWI &40755): Converts RISC OS RGB colours to industry standard CIE colours */
int ColourTrans_ConvertRGBToCIE(int r0, int r1, int r2, int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x40755" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToCMYK (SWI &4075A): Converts RISC OS RGB colours into the CMYK model */
int ColourTrans_ConvertRGBToCMYK(int r0, int r1, int r2, int *out_r1, int *out_r2, int *out_r3)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3");
    __asm__ volatile("swi 0x4075A" : "+r"(reg0), "+r"(reg1), "+r"(reg2), "=r"(reg3) : : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_ConvertRGBToHSV (SWI &40758): Converts RISC OS RGB colours into corresponding hue, saturation and value */
int ColourTrans_ConvertRGBToHSV(int r0, int r1, int r2, int *out_r1, int *out_r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x40758" : "+r"(reg0), "+r"(reg1), "+r"(reg2) : : "r3", "r12", "lr", "memory");
    if (out_r2) *out_r2 = reg2;
    if (out_r1) *out_r1 = reg1;
    return reg0;
}

/* ColourTrans_GCOLToColourNumber (SWI &4074C): Translates a GCOL to a colour number */
int ColourTrans_GCOLToColourNumber(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x4074C" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_GenerateTable (SWI &40763): This call is exactly the same as ColourTrans_SelectTable (see page 3-344), except that it */
void ColourTrans_GenerateTable(void)
{
    __asm__ volatile("swi 0x40763" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_InvalidateCache (SWI &40750): Informs ColourTrans that the palette has been changed by some other means */
void ColourTrans_InvalidateCache(void)
{
    __asm__ volatile("swi 0x40750" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_MiscOp (SWI &4075F): This call is for internal use only. It is not available in RISC OS 2 */
void ColourTrans_MiscOp(void)
{
    __asm__ volatile("swi 0x4075F" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_ReadCalibration (SWI &40752): Reads the calibration table for the screen */
int ColourTrans_ReadCalibration(void *buffer)
{
    register void * reg0 __asm("r0") = buffer;
    register int reg1 __asm("r1");
    __asm__ volatile("swi 0x40752" : "=r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* ColourTrans_ReturnColourNumber (SWI &40744): Gets the closest colour for a palette entry */
int ColourTrans_ReturnColourNumber(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40744" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnColourNumberForMode (SWI &40746): Gets the closest colour for a palette entry */
int ColourTrans_ReturnColourNumberForMode(int r0, int r1, void *r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register void * reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x40746" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnFontColours (SWI &4074E): Finds the best range of anti-alias colours to match a pair of palette entries */
int ColourTrans_ReturnFontColours(int handle, int r1, int r2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x4074E" : "+r"(reg2), "+r"(reg3) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg2;
}

/* ColourTrans_ReturnGCOL (SWI &40742): Gets the closest GCOL for a palette entry */
int ColourTrans_ReturnGCOL(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40742" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnGCOLForMode (SWI &40745): Gets the closest GCOL for a palette entry */
int ColourTrans_ReturnGCOLForMode(int r0, int r1, void *r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register void * reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x40745" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppColourNumber (SWI &40749): Gets the furthest colour for a palette entry */
int ColourTrans_ReturnOppColourNumber(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40749" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppColourNumberForMode (SWI &4074B): Gets the furthest colour for a palette entry */
int ColourTrans_ReturnOppColourNumberForMode(int r0, int r1, void *r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register void * reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x4074B" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppGCOL (SWI &40747): Gets the furthest GCOL for a palette entry */
int ColourTrans_ReturnOppGCOL(int r0)
{
    register int reg0 __asm("r0") = r0;
    __asm__ volatile("swi 0x40747" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_ReturnOppGCOLForMode (SWI &4074A): Gets the furthest GCOL for a palette entry */
int ColourTrans_ReturnOppGCOLForMode(int r0, int r1, void *r2)
{
    register int reg0 __asm("r0") = r0;
    register int reg1 __asm("r1") = r1;
    register void * reg2 __asm("r2") = r2;
    __asm__ volatile("swi 0x4074A" : "+r"(reg0) : "r"(reg1), "r"(reg2) : "r3", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_SetCalibration (SWI &40751): Sets the calibration table for the screen */
void ColourTrans_SetCalibration(void *ptr)
{
    register void * reg0 __asm("r0") = ptr;
    __asm__ volatile("swi 0x40751" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_SetFontColours (SWI &4074F): Sets the best range of anti-alias colours to match a pair of palette entries */
int ColourTrans_SetFontColours(int handle, int r1, int r2, int r3, int *out_r3)
{
    register int reg0 __asm("r0") = handle;
    register int reg1 __asm("r1") = r1;
    register int reg2 __asm("r2") = r2;
    register int reg3 __asm("r3") = r3;
    __asm__ volatile("swi 0x4074F" : "+r"(reg2), "+r"(reg3) : "r"(reg0), "r"(reg1) : "r12", "lr", "memory");
    if (out_r3) *out_r3 = reg3;
    return reg2;
}

/* ColourTrans_SetOppTextColour (SWI &40762): Changes the text foreground or background colour to a GCOL number */
int ColourTrans_SetOppTextColour(int r0, int flags)
{
    register int reg0 __asm("r0") = r0;
    register int reg3 __asm("r3") = flags;
    __asm__ volatile("swi 0x40762" : "+r"(reg0) : "r"(reg3) : "r1", "r2", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_SetTextColour (SWI &40761): Changes the text foreground or background colour to a GCOL number */
int ColourTrans_SetTextColour(int r0, int flags)
{
    register int reg0 __asm("r0") = r0;
    register int reg3 __asm("r3") = flags;
    __asm__ volatile("swi 0x40761" : "+r"(reg0) : "r"(reg3) : "r1", "r2", "r12", "lr", "memory");
    return reg0;
}

/* ColourTrans_WriteCalibrationToFile (SWI &40757): Saves the current calibration to a file */
void ColourTrans_WriteCalibrationToFile(int flags, int handle)
{
    register int reg0 __asm("r0") = flags;
    register int reg1 __asm("r1") = handle;
    __asm__ volatile("swi 0x40757" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* ColourTrans_WriteLoadingsToFile (SWI &40760): Writes a * Command to a file that will set the ColourTrans error loadings */
void ColourTrans_WriteLoadingsToFile(int handle)
{
    register int reg1 __asm("r1") = handle;
    __asm__ volatile("swi 0x40760" : : "r"(reg1) : "r0", "r2", "r3", "r12", "lr", "memory");
}
