/* RISC OS DOSFS SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* DOSFS_DiscFormat (SWI &44B00). See PRM 2-335. */
void DOSFS_DiscFormat(void *ptr, int swi, int parameter, int format)
{
    register void * reg0 __asm("r0") = ptr;
    register int reg1 __asm("r1") = swi;
    register int reg2 __asm("r2") = parameter;
    register int reg3 __asm("r3") = format;
    __asm__ volatile("swi 0x44B00" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* DOSFS_LayoutStructure (SWI &44B01). See PRM 2-338. */
void DOSFS_LayoutStructure(int structure, void *block, void *ptr, int file)
{
    register int reg0 __asm("r0") = structure;
    register void * reg1 __asm("r1") = block;
    register void * reg2 __asm("r2") = ptr;
    register int reg3 __asm("r3") = file;
    __asm__ volatile("swi 0x44B01" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}
