/* RISC OS Sound SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* Sound_AttachNamedVoice (SWI &4018A). See PRM 4-43. */
void Sound_AttachNamedVoice(int channel, void *string)
{
    register int reg0 __asm("r0") = channel;
    register void * reg1 __asm("r1") = string;
    __asm__ volatile("swi 0x4018A" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* Sound_AttachVoice (SWI &40185). See PRM 4-37. */
int Sound_AttachVoice(int channel, int voice)
{
    register int reg0 __asm("r0") = channel;
    register int reg1 __asm("r1") = voice;
    __asm__ volatile("swi 0x40185" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* Sound_Control (SWI &40189). See PRM 4-41. */
void Sound_Control(int channel, int date, int pitch, int time)
{
    register int reg0 __asm("r0") = channel;
    register int reg1 __asm("r1") = date;
    register int reg2 __asm("r2") = pitch;
    register int reg3 __asm("r3") = time;
    __asm__ volatile("swi 0x40189" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* Sound_ControlPacked (SWI &40186). See PRM 4-38. */
void Sound_ControlPacked(int aaaacccc, int ddddpppp)
{
    register int reg0 __asm("r0") = aaaacccc;
    register int reg1 __asm("r1") = ddddpppp;
    __asm__ volatile("swi 0x40186" : : "r"(reg0), "r"(reg1) : "r2", "r3", "r12", "lr", "memory");
}

/* Sound_Enable (SWI &40141). See PRM 4-20. */
int Sound_Enable(int new)
{
    register int reg0 __asm("r0") = new;
    __asm__ volatile("swi 0x40141" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_LogScale (SWI &40182). See PRM 4-28. */
int Sound_LogScale(int arg0)
{
    register int reg0 __asm("r0") = arg0;
    __asm__ volatile("swi 0x40182" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_Pitch (SWI &40188). See PRM 4-40. */
void Sound_Pitch(int value)
{
    register int reg0 __asm("r0") = value;
    __asm__ volatile("swi 0x40188" : : "r"(reg0) : "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Sound_QBeat (SWI &401C6). See PRM 4-54. */
int Sound_QBeat(int length)
{
    register int reg0 __asm("r0") = length;
    __asm__ volatile("swi 0x401C6" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_QFree (SWI &401C3). See PRM 4-51. */
int Sound_QFree(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x401C3" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_QInit (SWI &401C0). See PRM 4-47. */
int Sound_QInit(void)
{
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x401C0" : "=r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_QInterface (SWI &401C7). See PRM 4-56. */
void Sound_QInterface(void)
{
    __asm__ volatile("swi 0x401C7" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Sound_QRemove (SWI &401C2). See PRM 4-50. */
void Sound_QRemove(void)
{
    __asm__ volatile("swi 0x401C2" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Sound_QSDispatch (SWI &401C4). See PRM 4-52. */
void Sound_QSDispatch(void)
{
    __asm__ volatile("swi 0x401C4" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* Sound_QSchedule (SWI &401C1). See PRM 4-48. */
int Sound_QSchedule(int schedule, int arg1, int swi, int swi2)
{
    register int reg0 __asm("r0") = schedule;
    register int reg1 __asm("r1") = arg1;
    register int reg2 __asm("r2") = swi;
    register int reg3 __asm("r3") = swi2;
    __asm__ volatile("swi 0x401C1" : "+r"(reg0) : "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
    return reg0;
}

/* Sound_QTempo (SWI &401C5). See PRM 4-53. */
int Sound_QTempo(int new)
{
    register int reg0 __asm("r0") = new;
    __asm__ volatile("swi 0x401C5" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_ReadControlBlock (SWI &4018B). See PRM 4-44. */
int Sound_ReadControlBlock(int channel, int offset)
{
    register int reg0 __asm("r0") = channel;
    register int reg1 __asm("r1") = offset;
    register int reg2 __asm("r2");
    __asm__ volatile("swi 0x4018B" : "=r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}

/* Sound_RemoveVoice (SWI &40184). See PRM 4-35. */
int Sound_RemoveVoice(int voice, int *out_voice)
{
    register int reg1 __asm("r1") = voice;
    register int reg0 __asm("r0");
    __asm__ volatile("swi 0x40184" : "+r"(reg1), "=r"(reg0) : : "r2", "r3", "r12", "lr", "memory");
    if (out_voice) *out_voice = reg1;
    return reg0;
}

/* Sound_SoundLog (SWI &40181). See PRM 4-27. */
int Sound_SoundLog(int arg0)
{
    register int reg0 __asm("r0") = arg0;
    __asm__ volatile("swi 0x40181" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_Speaker (SWI &40143). See PRM 4-24. */
int Sound_Speaker(int new)
{
    register int reg0 __asm("r0") = new;
    __asm__ volatile("swi 0x40143" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_Stereo (SWI &40142). See PRM 4-22. */
int Sound_Stereo(int channel, int image)
{
    register int reg0 __asm("r0") = channel;
    register int reg1 __asm("r1") = image;
    __asm__ volatile("swi 0x40142" : "+r"(reg1) : "r"(reg0) : "r2", "r3", "r12", "lr", "memory");
    return reg1;
}

/* Sound_Tuning (SWI &40187). See PRM 4-39. */
int Sound_Tuning(int value)
{
    register int reg0 __asm("r0") = value;
    __asm__ volatile("swi 0x40187" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_Volume (SWI &40180). See PRM 4-26. */
int Sound_Volume(int sound)
{
    register int reg0 __asm("r0") = sound;
    __asm__ volatile("swi 0x40180" : "+r"(reg0) : : "r1", "r2", "r3", "r12", "lr", "memory");
    return reg0;
}

/* Sound_WriteControlBlock (SWI &4018C). See PRM 4-45. */
int Sound_WriteControlBlock(int channel, int offset, int arg2)
{
    register int reg0 __asm("r0") = channel;
    register int reg1 __asm("r1") = offset;
    register int reg2 __asm("r2") = arg2;
    __asm__ volatile("swi 0x4018C" : "+r"(reg2) : "r"(reg0), "r"(reg1) : "r3", "r12", "lr", "memory");
    return reg2;
}
