/* RISC OS FileCore SWI shims — generated by gen_riscos_pkg.py.
 * One C function per SWI, named exactly like the SWI, so the
 * Mojo bindings' external_call names resolve here. */

/* FileCore_DiscFormat (SWI &40547). See PRM 2-236. */
void FileCore_DiscFormat(void *ptr, int swi, int parameter, int format)
{
    register void * reg0 __asm("r0") = ptr;
    register int reg1 __asm("r1") = swi;
    register int reg2 __asm("r2") = parameter;
    register int reg3 __asm("r3") = format;
    __asm__ volatile("swi 0x40547" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* FileCore_DiscOp (SWI &40540). See PRM 2-224. */
void FileCore_DiscOp(void)
{
    __asm__ volatile("swi 0x40540" : : : "r0", "r1", "r2", "r3", "r12", "lr", "memory");
}

/* FileCore_FloppyStructure (SWI &40544). See PRM 2-232. */
void FileCore_FloppyStructure(void *buffer, void *ptr, int arg2, void *ptr2)
{
    register void * reg0 __asm("r0") = buffer;
    register void * reg1 __asm("r1") = ptr;
    register int reg2 __asm("r2") = arg2;
    register void * reg3 __asm("r3") = ptr2;
    __asm__ volatile("swi 0x40544" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}

/* FileCore_LayoutStructure (SWI &40548). See PRM 2-239. */
void FileCore_LayoutStructure(int identifier, void *block, void *ptr, int file)
{
    register int reg0 __asm("r0") = identifier;
    register void * reg1 __asm("r1") = block;
    register void * reg2 __asm("r2") = ptr;
    register int reg3 __asm("r3") = file;
    __asm__ volatile("swi 0x40548" : : "r"(reg0), "r"(reg1), "r"(reg2), "r"(reg3) : "r12", "lr", "memory");
}
