@ roclib veneer table — GENERATED by tools/clibspec/gen_veneers.py
@ One MOV pc,#0 per module entry; SharedCLibrary patches each slot
@ at LibInitAPCS_32.  Slot N is the module's Nth entry: order is the contract.

    .syntax unified
    .arm

    .section Stub$$Init
    .global _clib_stub_init
_clib_stub_init:
    .word 9
    .word _clib_entries_start
    .word _clib_entries_end
    .word 0
    .word 0

    .section Stub$$Entries,"ax",%progbits
    .global _clib_entries_start
    .global _clib_entries_end
    .align 2
_clib_entries_start:
.global TrapHandler
TrapHandler:
    .word 0xE3A0F000
.global UncaughtTrapHandler
UncaughtTrapHandler:
    .word 0xE3A0F000
.global EventHandler
EventHandler:
    .word 0xE3A0F000
.global UnhandledEventHandler
UnhandledEventHandler:
    .word 0xE3A0F000
.global x$stack_overflow
.global __rt_stkovf_split_small
__rt_stkovf_split_small:
x$stack_overflow:
    .word 0xE3A0F000
.global x$stack_overflow_1
.global __rt_stkovf_split_big
__rt_stkovf_split_big:
x$stack_overflow_1:
    .word 0xE3A0F000
.global x$udivide
.global __rt_udiv
__rt_udiv:
x$udivide:
    .word 0xE3A0F000
.global x$uremainder
x$uremainder:
    .word 0xE3A0F000
.global x$divide
.global __rt_sdiv
__rt_sdiv:
x$divide:
    .word 0xE3A0F000
.global x$divtest
.global __rt_divtest
__rt_divtest:
x$divtest:
    .word 0xE3A0F000
.global x$remainder
x$remainder:
    .word 0xE3A0F000
.global x$multiply
x$multiply:
    .word 0xE3A0F000
.global _rd1chk
.global __rt_rd1chk
__rt_rd1chk:
_rd1chk:
    .word 0xE3A0F000
.global _rd2chk
.global __rt_rd2chk
__rt_rd2chk:
_rd2chk:
    .word 0xE3A0F000
.global _rd4chk
.global __rt_rd4chk
__rt_rd4chk:
_rd4chk:
    .word 0xE3A0F000
.global _wr1chk
.global __rt_wr1chk
__rt_wr1chk:
_wr1chk:
    .word 0xE3A0F000
.global _wr2chk
.global __rt_wr2chk
__rt_wr2chk:
_wr2chk:
    .word 0xE3A0F000
.global _wr4chk
.global __rt_wr4chk
__rt_wr4chk:
_wr4chk:
    .word 0xE3A0F000
.global _main
_main:
    .word 0xE3A0F000
.global _exit
_exit:
    .word 0xE3A0F000
.global _clib_initialise
_clib_initialise:
    .word 0xE3A0F000
.global _backtrace
_backtrace:
    .word 0xE3A0F000
.global _count
_count:
    .word 0xE3A0F000
.global _count1
_count1:
    .word 0xE3A0F000
.global _stfp
_stfp:
    .word 0xE3A0F000
.global _ldfp
_ldfp:
    .word 0xE3A0F000
.global _printf
_printf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global _fprintf
_fprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global _sprintf
_sprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global clock
clock:
    .word 0xE3A0F000
.global difftime
difftime:
    .word 0xE3A0F000 @ unsafe class: slot only
.global mktime
mktime:
    .word 0xE3A0F000
.global time
time:
    .word 0xE3A0F000
.global asctime
asctime:
    .word 0xE3A0F000
.global ctime
ctime:
    .word 0xE3A0F000
.global gmtime
gmtime:
    .word 0xE3A0F000
.global localtime
localtime:
    .word 0xE3A0F000
.global strftime
strftime:
    .word 0xE3A0F000
.global memcpy
memcpy:
    .word 0xE3A0F000
.global memmove
memmove:
    .word 0xE3A0F000
.global strcpy
strcpy:
    .word 0xE3A0F000
.global strncpy
strncpy:
    .word 0xE3A0F000
.global strcat
strcat:
    .word 0xE3A0F000
.global strncat
strncat:
    .word 0xE3A0F000
.global memcmp
memcmp:
    .word 0xE3A0F000
.global strcmp
strcmp:
    .word 0xE3A0F000
.global strncmp
strncmp:
    .word 0xE3A0F000
.global memchr
memchr:
    .word 0xE3A0F000
.global strchr
strchr:
    .word 0xE3A0F000
.global strcspn
strcspn:
    .word 0xE3A0F000
.global strpbrk
strpbrk:
    .word 0xE3A0F000
.global strrchr
strrchr:
    .word 0xE3A0F000
.global strspn
strspn:
    .word 0xE3A0F000
.global strstr
strstr:
    .word 0xE3A0F000
.global strtok
strtok:
    .word 0xE3A0F000
.global memset
memset:
    .word 0xE3A0F000
.global strerror
strerror:
    .word 0xE3A0F000
.global strlen
strlen:
    .word 0xE3A0F000
.global atof
atof:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atoi
atoi:
    .word 0xE3A0F000
.global atol
atol:
    .word 0xE3A0F000
.global strtod
strtod:
    .word 0xE3A0F000 @ unsafe class: slot only
.global strtol
strtol:
    .word 0xE3A0F000
.global strtoul
strtoul:
    .word 0xE3A0F000
.global rand
rand:
    .word 0xE3A0F000
.global srand
srand:
    .word 0xE3A0F000
.global calloc
calloc:
    .word 0xE3A0F000
.global free
free:
    .word 0xE3A0F000
.global malloc
malloc:
    .word 0xE3A0F000
.global realloc
realloc:
    .word 0xE3A0F000
.global abort
abort:
    .word 0xE3A0F000
.global atexit
atexit:
    .word 0xE3A0F000
.global exit
exit:
    .word 0xE3A0F000
.global getenv
getenv:
    .word 0xE3A0F000
.global system
system:
    .word 0xE3A0F000
.global bsearch
bsearch:
    .word 0xE3A0F000
.global qsort
qsort:
    .word 0xE3A0F000
.global abs
abs:
    .word 0xE3A0F000
.global div
div:
    .word 0xE3A0F000 @ unsafe class: slot only
.global labs
labs:
    .word 0xE3A0F000
.global ldiv
ldiv:
    .word 0xE3A0F000 @ unsafe class: slot only
.global remove
remove:
    .word 0xE3A0F000
.global rename
rename:
    .word 0xE3A0F000
.global tmpfile
tmpfile:
    .word 0xE3A0F000
.global __old_tmpnam
__old_tmpnam:
    .word 0xE3A0F000
.global fclose
fclose:
    .word 0xE3A0F000
.global fflush
fflush:
    .word 0xE3A0F000
.global fopen
fopen:
    .word 0xE3A0F000
.global freopen
freopen:
    .word 0xE3A0F000
.global setbuf
setbuf:
    .word 0xE3A0F000
.global setvbuf
setvbuf:
    .word 0xE3A0F000
.global printf
printf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global fprintf
fprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global sprintf
sprintf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global scanf
scanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global fscanf
fscanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global sscanf
sscanf:
    .word 0xE3A0F000 @ varargs entry: not callable from AAPCS
.global vprintf
vprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vfprintf
vfprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global vsprintf
vsprintf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global _vfprintf
_vfprintf:
    .word 0xE3A0F000
.global fgetc
fgetc:
    .word 0xE3A0F000
.global fgets
fgets:
    .word 0xE3A0F000
.global fputc
fputc:
    .word 0xE3A0F000
.global fputs
fputs:
    .word 0xE3A0F000
.global __filbuf
__filbuf:
    .word 0xE3A0F000
.global getc
getc:
    .word 0xE3A0F000
.global getchar
getchar:
    .word 0xE3A0F000
.global gets
gets:
    .word 0xE3A0F000
.global __flsbuf
__flsbuf:
    .word 0xE3A0F000
.global putc
putc:
    .word 0xE3A0F000
.global putchar
putchar:
    .word 0xE3A0F000
.global puts
puts:
    .word 0xE3A0F000
.global ungetc
ungetc:
    .word 0xE3A0F000
.global fread
fread:
    .word 0xE3A0F000
.global fwrite
fwrite:
    .word 0xE3A0F000
.global fgetpos
fgetpos:
    .word 0xE3A0F000
.global fseek
.global _fseeko
_fseeko:
fseek:
    .word 0xE3A0F000
.global fsetpos
fsetpos:
    .word 0xE3A0F000
.global ftell
.global _ftello
_ftello:
ftell:
    .word 0xE3A0F000
.global rewind
rewind:
    .word 0xE3A0F000
.global clearerr
clearerr:
    .word 0xE3A0F000
.global feof
feof:
    .word 0xE3A0F000
.global ferror
ferror:
    .word 0xE3A0F000
.global perror
perror:
    .word 0xE3A0F000
.global __ignore_signal_handler
__ignore_signal_handler:
    .word 0xE3A0F000
.global __default_signal_handler
__default_signal_handler:
    .word 0xE3A0F000
.global __error_signal_marker
__error_signal_marker:
    .word 0xE3A0F000
.global signal
signal:
    .word 0xE3A0F000
.global raise
raise:
    .word 0xE3A0F000
.global setjmp
setjmp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global longjmp
longjmp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global acos
acos:
    .word 0xE3A0F000 @ unsafe class: slot only
.global asin
asin:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atan
atan:
    .word 0xE3A0F000 @ unsafe class: slot only
.global atan2
atan2:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cos
cos:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sin
sin:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tan
tan:
    .word 0xE3A0F000 @ unsafe class: slot only
.global cosh
cosh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sinh
sinh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global tanh
tanh:
    .word 0xE3A0F000 @ unsafe class: slot only
.global exp
exp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global frexp
frexp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ldexp
ldexp:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log
log:
    .word 0xE3A0F000 @ unsafe class: slot only
.global log10
log10:
    .word 0xE3A0F000 @ unsafe class: slot only
.global modf
modf:
    .word 0xE3A0F000 @ unsafe class: slot only
.global pow
pow:
    .word 0xE3A0F000 @ unsafe class: slot only
.global sqrt
sqrt:
    .word 0xE3A0F000 @ unsafe class: slot only
.global ceil
ceil:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fabs
fabs:
    .word 0xE3A0F000 @ unsafe class: slot only
.global floor
floor:
    .word 0xE3A0F000 @ unsafe class: slot only
.global fmod
fmod:
    .word 0xE3A0F000 @ unsafe class: slot only
.global setlocale
setlocale:
    .word 0xE3A0F000
.global isalnum
isalnum:
    .word 0xE3A0F000
.global isalpha
isalpha:
    .word 0xE3A0F000
.global iscntrl
iscntrl:
    .word 0xE3A0F000
.global isdigit
isdigit:
    .word 0xE3A0F000
.global isgraph
isgraph:
    .word 0xE3A0F000
.global islower
islower:
    .word 0xE3A0F000
.global isprint
isprint:
    .word 0xE3A0F000
.global ispunct
ispunct:
    .word 0xE3A0F000
.global isspace
isspace:
    .word 0xE3A0F000
.global isupper
isupper:
    .word 0xE3A0F000
.global isxdigit
isxdigit:
    .word 0xE3A0F000
.global tolower
tolower:
    .word 0xE3A0F000
.global toupper
toupper:
    .word 0xE3A0F000
.global __assert
__assert:
    .word 0xE3A0F000
.global _memcpy
_memcpy:
    .word 0xE3A0F000
.global _memset
_memset:
    .word 0xE3A0F000
.global localeconv
localeconv:
    .word 0xE3A0F000
.global mblen
mblen:
    .word 0xE3A0F000
.global mbtowc
mbtowc:
    .word 0xE3A0F000
.global wctomb
wctomb:
    .word 0xE3A0F000
.global mbstowcs
mbstowcs:
    .word 0xE3A0F000
.global wcstombs
wcstombs:
    .word 0xE3A0F000
.global strxfrm
strxfrm:
    .word 0xE3A0F000
.global strcoll
strcoll:
    .word 0xE3A0F000
.global _clib_finalisemodule
_clib_finalisemodule:
    .word 0xE3A0F000
.global _clib_version
_clib_version:
    .word 0xE3A0F000
.global _CLib_Finalise
_CLib_Finalise:
    .word 0xE3A0F000
.global tmpnam
tmpnam:
    .word 0xE3A0F000
.global _swi
_swi:
    .word 0xE3A0F000 @ unsafe class: slot only
.global _swix
_swix:
    .word 0xE3A0F000 @ unsafe class: slot only
_clib_entries_end:

